"use strict";

function renderTerrain() {
  const stats=signalStats(),tabs=`<div class="tabs"><button class="tab ${state.terrainTab==="signals"?"active":""}" data-terrain-tab="signals">Signaux</button><button class="tab ${state.terrainTab==="gemba"?"active":""}" data-terrain-tab="gemba">Gemba</button><button class="tab ${state.terrainTab==="stats"?"active":""}" data-terrain-tab="stats">Statistiques</button><button class="tab" data-nav="audits">Audit Terrain · 50 critères</button></div>`;
  if(state.terrainTab==="gemba")return `${pageHead("Terrain","Gemba","Observer, comprendre avec l’équipe, décider et revenir vérifier.",'<button class="btn" data-new-gemba>＋ Nouveau Gemba</button>')}${tabs}${renderGembaList()}`;
  if(state.terrainTab==="stats")return `${pageHead("Terrain","Statistiques des signaux","Délais calculés uniquement sur les événements réellement horodatés.")}${tabs}${renderSignalStats(stats)}`;
  let rows=scoped(data.signals).sort((a,b)=>String(b.created_at).localeCompare(String(a.created_at)));
  rows=rows.filter(s=>state.signalFilter==="all"||state.signalFilter==="open"&&isOpenSignal(s)||state.signalFilter==="critical"&&s.severity==="Critique"&&isOpenSignal(s)||state.signalFilter==="new"&&s.state==="Nouveau"||state.signalFilter==="closed"&&s.state==="Clos");
  return `${pageHead("Terrain","Signal Terrain","Un fait, une prise en charge, une réponse vérifiée.",'<button class="btn" data-new-signal>＋ NOUVEAU SIGNAL TERRAIN</button>')}${tabs}<div class="filters">${[["open",`Ouverts · ${stats.open}`],["new",`Nouveaux · ${stats.new}`],["critical",`Critiques · ${stats.critical}`],["closed","Clos"],["all","Tous"]].map(([key,label])=>`<button class="chip ${key===state.signalFilter?"active":""}" data-signal-filter="${key}">${label}</button>`).join("")}</div>${listSearch("Rechercher un signal")}<div class="list section">${rows.map(signalCard).join("")||empty("Aucun signal pour ce filtre sur le site sélectionné.")}</div>`;
}
function elapsedMedian(rows,endKey,startKey="created_at") {
  const valid=rows.filter(s=>s[startKey]&&s[endKey]).map(s=>(Date.parse(s[endKey])-Date.parse(s[startKey]))/3600000).filter(n=>Number.isFinite(n)&&n>=0).sort((a,b)=>a-b);
  const mid=Math.floor(valid.length/2);return {count:valid.length,hours:valid.length?(valid.length%2?valid[mid]:(valid[mid-1]+valid[mid])/2):null};
}
function renderSignalStats(stats) {
  const rows=scoped(data.signals),taken=elapsedMedian(rows,"taken_at"),resolved=elapsedMedian(rows,"resolved_at"),byMonth={};
  rows.forEach(s=>{if(s.created_at){const month=s.created_at.slice(0,7);byMonth[month]=(byMonth[month]||0)+1;}});
  return `<div class="grid cols-4">${[["Signaux ouverts",stats.open],["Nouveaux",stats.new],["Prise en charge médiane",taken.hours===null?"—":`${taken.hours.toFixed(1)} h`],["Résolution médiane",resolved.hours===null?"—":`${resolved.hours.toFixed(1)} h`]].map(([title,value])=>`<article class="card"><div class="metric-label">${title}</div><div class="metric-value">${value}</div></article>`).join("")}</div><p class="hint">Prise en charge : ${taken.count}/${rows.length} signaux horodatés · Résolution : ${resolved.count}/${rows.length}. Les anciens signaux sans historique ne sont pas inclus dans les délais.</p><div class="grid cols-2 section"><section class="panel"><h2>Par catégorie</h2>${SIGNAL_TYPES.map(type=>{const count=rows.filter(s=>s.type===type).length;return `<p><b>${esc(type)}</b> · ${count}</p><div class="progress"><span style="width:${rows.length?100*count/rows.length:0}%"></span></div>`;}).join("")}</section><section class="panel"><h2>Remontées par mois</h2>${Object.entries(byMonth).sort().map(([month,count])=>`<div class="row"><b>${month}</b><span>${count} signal(s)</span></div>`).join("")||empty("Aucun signal daté.")}<p class="hint">Une hausse des remontées peut traduire une meilleure expression du terrain.</p></section></div>`;
}
function measureFor(axis) {return scoped(data.measures,{groupAllowed:false}).filter(m=>m.axis===axis).sort((a,b)=>String(b.period).localeCompare(String(a.period)))[0];}
function topSubjects() {
  if(state.site==="group")return [];
  const topics=scoped(data.topics).filter(t=>t.status!=="Clos").map(t=>({id:t.id,category:AXES[t.axis]?.label||"Sujet",title:t.title,next:t.owner,due:shortDate(t.due_date),priority:t.priority}));
  const covered=new Set(scoped(data.topics).filter(t=>t.status!=="Clos").map(t=>t.linked_id).filter(Boolean));
  const signals=scoped(data.signals).filter(s=>isOpenSignal(s)&&s.state!=="Vérifié"&&!covered.has(s.id)).map(s=>({id:s.id,category:s.type,title:s.description,next:signalNextLabel(s),due:"Aujourd’hui",priority:s.severity}));
  const actions=scoped(data.actions).filter(a=>isOpenAction(a)&&!covered.has(a.id)&&(isLate(a)||a.status==="À vérifier"||["Critique","Haute"].includes(a.priority))).map(a=>({id:a.id,category:"Action",title:a.title,next:a.owner,due:shortDate(a.due_date),priority:a.priority}));
  const decisions=scoped(data.decisions).filter(d=>d.status!=="Clos").map(d=>({id:d.id,category:"Décision",title:d.title,next:d.owner,due:shortDate(d.due_date),priority:"Haute"}));
  return [...topics,...signals,...actions,...decisions].sort((a,b)=>({Critique:0,Haute:1,Normale:2}[a.priority]??3)-({Critique:0,Haute:1,Normale:2}[b.priority]??3));
}
function renderSqcdp() {
  if(state.site==="group")return `${pageHead("SQCDP Atelier","Choisir une entité","Le point quotidien se tient au niveau du terrain.")}<div class="grid cols-3">${OPERATIONAL_SITES.map(s=>`<button class="card" data-set-site="${s.id}">${esc(s.name)} →</button>`).join("")}</div>`;
  const subjects=topSubjects();
  return `${pageHead("Point quotidien",`SQCDP · ${site().name}`,`${workshop()?.name||"Atelier à préciser"} · ${shortDate(today())}`,'<div class="row-actions"><button class="btn secondary" data-display-mode>'+ (state.presentation?"Quitter l’écran atelier":"Écran atelier")+'</button><button class="btn" data-new-signal>＋ SIGNAL TERRAIN</button></div>')}<div class="sqcdp-grid section">${Object.entries(AXES).map(([axis,def])=>{const m=measureFor(axis),s=measureStatus(m);return `<article class="sqcdp-card" style="--axis:${def.color}"><h3><span class="axis-letter">${axis}</span>${esc(def.label)}</h3><div class="metric-label">${esc(m?.label||"Indicateur à définir")}</div><div class="sqcdp-value">${m?.value??"—"} <small>${esc(m?.unit||"")}</small></div><p>Cible : ${m?.target??"—"} ${esc(m?.unit||"")}</p>${pill(s.text,s.tone)}<p class="source-label">${esc(m?.source||"Source à connecter")} · ${shortDate(m?.period)}</p>${m?.value!=null?`<button class="btn secondary small" data-topic-axis="${axis}" data-topic-title="${esc(`Écart ${m.label} : ${m.value} ${m.unit} / cible ${m.target??"à définir"}`)}">Traiter un écart</button>`:""}</article>`;}).join("")}</div><section class="section"><div class="section-title"><div><h2>TOP 15 · À traiter aujourd’hui</h2><p class="hint">${subjects.length} sujet(s) · le TOP 15 désigne le rituel, pas un nombre de lignes.</p></div><div class="row-actions"><span class="timer" id="meetingTimer">${timerLabel()}</span><button class="btn secondary" data-timer>${state.timerStarted?"Arrêter":"Démarrer"} le point</button><button class="btn" data-new-topic>＋ Ajouter un sujet</button></div></div><div class="list">${subjects.map((s,i)=>`<article class="row top15-row"><b>${i+1} · ${esc(s.category)}</b><div><h3>${esc(s.title)}</h3><span class="hint">${esc(s.id)}</span></div><span>${esc(s.next)}</span><span>${esc(s.due)}</span><div>${pill(s.priority,s.priority==="Critique"?"critical":"progress")}${recordLink(s.id,"Traiter")}</div></article>`).join("")||empty("Aucun sujet ouvert. Ajoutez un écart ou un engagement pour l’équipe.")}</div></section>`;
}
function timerLabel() {const s=state.timerStarted?Math.floor((Date.now()-state.timerStarted)/1000):0;return `${String(Math.floor(s/60)).padStart(2,"0")}:${String(s%60).padStart(2,"0")}`;}
function topicForm(existing=null,preset={}) {
  const siteId=existing?.site_id||(state.site==="group"?"marzin":state.site),available=[...data.signals,...data.problems,...data.actions].filter(r=>r.site_id===siteId);
  modal(existing?`${existing.id} · Sujet TOP 15`:"Ajouter un sujet au TOP 15",`<form id="topicForm"><div class="form-grid"><label class="wide">Que devons-nous traiter ?<input id="topicTitle" required value="${esc(existing?.title||preset.title||"")}"></label><label>Axe<select id="topicAxis">${Object.entries(AXES).map(([key,a])=>`<option value="${key}" ${key===(existing?.axis||preset.axis)?"selected":""}>${key} · ${esc(a.label)}</option>`).join("")}</select></label><label>Responsable<input id="topicOwner" required value="${esc(existing?.owner||"")}"></label><label>Échéance<input type="date" id="topicDate" required value="${existing?.due_date||today()}"></label><label>Priorité<select id="topicPriority">${["Normale","Haute","Critique"].map(p=>`<option ${p===existing?.priority?"selected":""}>${p}</option>`).join("")}</select></label><label class="wide">Dossier déjà existant<select id="topicLink"><option value="">Aucun dossier associé</option>${available.map(r=>`<option value="${r.id}" ${r.id===existing?.linked_id?"selected":""}>${esc(r.id)} · ${esc(r.title||r.description)}</option>`).join("")}</select></label><label>Statut<select id="topicStatus">${["Ouvert","En cours","Clos"].map(s=>`<option ${s===existing?.status?"selected":""}>${s}</option>`).join("")}</select></label><label class="wide">Décision / résultat<textarea id="topicDecision" rows="3">${esc(existing?.decision||"")}</textarea></label></div>${existing?`${relatedPanel(existing.id)}<div class="row-actions">${recordLink(existing.linked_id,"Dossier associé")}${recordLink(existing.escalation_id,"Escalade")}<button type="button" class="btn secondary" data-new-action data-origin-type="TOP 15" data-origin-id="${existing.id}">Créer une action</button>${!existing.escalation_id?`<button type="button" class="btn secondary" data-escalate-topic="${existing.id}">Demander une décision</button>`:""}</div>`:""}<div class="form-actions"><button class="btn">Enregistrer le sujet</button><button type="button" class="btn secondary" data-close-modal>Annuler</button></div></form>`);
  $("topicForm").onsubmit=e=>{e.preventDefault();const row={...existing,id:existing?.id||nextId("TOP",data.topics),site_id:siteId,title:$("topicTitle").value.trim(),axis:$("topicAxis").value,owner:$("topicOwner").value.trim(),due_date:$("topicDate").value,priority:$("topicPriority").value,linked_id:$("topicLink").value||null,status:$("topicStatus").value,decision:$("topicDecision").value.trim(),created_at:existing?.created_at||now(),updated_at:now()};if(!allowedSite(siteId,true)||!row.title||!row.owner)return toast("Précisez le sujet et le responsable.");if(row.status==="Clos"&&(!row.decision||linkedActions(row.id).some(isOpenAction)))return toast("Un résultat et la clôture des actions liées sont nécessaires.");if(!commitData(()=>{const old=data.topics.find(t=>t.id===row.id);if(old)Object.assign(old,row);else data.topics.unshift(row);}))return;closeModal();receipt(row.id,"SQCDP → TOP 15",siteId,"Sujet ajouté au point quotidien");render();};
  document.querySelectorAll("[data-escalate-topic]").forEach(b=>b.onclick=()=>{if(requestCloseModal())decisionForm(null,{site_id:siteId,title:existing.title,origin_id:existing.id});});
}
function decisionForm(existing=null,origin={}) {
  const siteId=existing?.site_id||origin.site_id||(state.site==="group"?"group":state.site);if(!allowedSite(siteId))return;
  modal(existing?`${existing.id} · Décision / escalade`:"Demander une décision",`<form id="decisionForm"><div class="form-grid"><label class="wide">Quelle décision attendez-vous ?<input id="decisionTitle" required value="${esc(existing?.title||origin.title||"")}"></label><label>Décideur<input id="decisionOwner" required value="${esc(existing?.owner||"")}"></label><label>Pour quand ?<input id="decisionDate" type="date" required value="${existing?.due_date||today()}"></label><label class="wide">Faits, impact et options<textarea id="decisionDetail" rows="3">${esc(existing?.detail||"")}</textarea></label><label>Statut<select id="decisionStatus">${["Ouverte","En cours","Clos"].map(s=>`<option ${s===existing?.status?"selected":""}>${s}</option>`).join("")}</select></label><label class="wide">Décision prise<textarea id="decisionResult" rows="3">${esc(existing?.result||"")}</textarea></label></div>${recordLink(existing?.origin_id,"Sujet d’origine")}${existing?relatedPanel(existing.id):""}<div class="form-actions"><button class="btn">Enregistrer la décision</button><button class="btn secondary" type="button" data-close-modal>Annuler</button></div></form>`);
  $("decisionForm").onsubmit=e=>{e.preventDefault();const row={...existing,id:existing?.id||nextId("D",data.decisions),site_id:siteId,title:$("decisionTitle").value.trim(),owner:$("decisionOwner").value.trim(),due_date:$("decisionDate").value,detail:$("decisionDetail").value.trim(),status:$("decisionStatus").value,result:$("decisionResult").value.trim(),origin_id:existing?.origin_id||origin.origin_id||null,updated_at:now()};if(!row.title||!row.owner||row.status==="Clos"&&!row.result)return toast("Précisez la décision attendue, son responsable et le résultat pour clore.");if(!commitData(()=>{const d=data.decisions.find(x=>x.id===row.id);if(d)Object.assign(d,row);else data.decisions.unshift(row);const t=data.topics.find(x=>x.id===row.origin_id);if(t)t.escalation_id=row.id;recordHistory(d||row,row.status,row.result);} ))return;closeModal();receipt(row.id,"Décisions / TOP 15",siteId,row.status);render();};
}
function lineChart(series,title,unit="") {
  const points=(series?.values||[]).map((value,i)=>({value,label:series.labels?.[i]||""})),valid=points.map(p=>p.value).filter(Number.isFinite);
  if(!valid.length)return empty("Historique indisponible.");
  const all=Number.isFinite(series.target)?[...valid,series.target]:valid,w=720,h=230,p=38,min=Math.min(...all),max=Math.max(...all),margin=Math.max((max-min)*.2,1),lo=Math.max(0,min-margin),hi=max+margin,x=i=>p+i*(w-2*p)/Math.max(1,points.length-1),y=v=>h-p-(v-lo)*(h-2*p)/(hi-lo||1);let path="",started=false;
  points.forEach((point,i)=>{if(!Number.isFinite(point.value)){started=false;return;}path+=`${started?"L":"M"}${x(i)},${y(point.value)} `;started=true;});
  return `<svg class="line-chart" viewBox="0 0 ${w} ${h}" role="img" aria-label="${esc(title)}">${Number.isFinite(series.target)?`<line class="chart-target" x1="${p}" y1="${y(series.target)}" x2="${w-p}" y2="${y(series.target)}"/><text class="chart-value" x="${w-160}" y="${y(series.target)-8}">Cible ${series.target} ${esc(unit)}</text>`:""}<path class="chart-line" d="${path}" fill="none"/>${points.map((point,i)=>`${Number.isFinite(point.value)?`<circle class="chart-point" cx="${x(i)}" cy="${y(point.value)}" r="5"/><text class="chart-value" x="${x(i)-10}" y="${y(point.value)-10}">${point.value}</text>`:""}<text class="chart-label" x="${x(i)-12}" y="${h-8}">${esc(point.label)}</text>`).join("")}</svg>`;
}
function indicatorSeries(siteId,code) {
  const legacy=data.trends.find(t=>t.site_id===siteId&&t.code===code),series=legacy?clone(legacy):null;
  if(!series)return null;const n=state.period==="all"?series.values.length:Number(state.period);series.values=series.values.slice(-n);series.labels=series.labels.slice(-n);return series;
}
function pilotageChart(series,{title,code,unit="%",direction="high",contextLabel=site().name}) {
  const has=series?.values?.some(Number.isFinite);if(!has)return `<article class="panel indicator-chart unavailable"><div class="section-title"><h2>${esc(title)}</h2>${pill("Donnée indisponible")}</div><p>Source et définition à qualifier. Source SEQUOIA à vérifier.</p></article>`;
  const last=series.values.at(-1),prev=series.values.at(-2),delta=Number.isFinite(last)&&Number.isFinite(prev)?+(last-prev).toFixed(1):null,target=series.target,gap=Number.isFinite(last)&&Number.isFinite(target)?+(last-target).toFixed(1):null,good=gap===null?null:direction==="low"?gap<=0:gap>=0,siteId=state.site==="group"?state.pilotSite:state.site,linked=data.actions.filter(a=>a.site_id===siteId&&a.origin_type==="KPI"&&a.origin_id===code).length;
  return `<article class="panel indicator-chart"><div class="section-title"><div><h2>${esc(title)}</h2><div class="metric-value">${Number.isFinite(last)?last:"—"} <small>${esc(unit)}</small></div></div>${pill(good===null?"À qualifier":good?"Conforme":"Écart",good===null?"neutral":good?"done":"open")}</div><p class="hint">Cible ${Number.isFinite(target)?target:"—"} ${esc(unit)} · Écart ${gap===null?"—":`${gap>0?"+":""}${gap}`} ${unit==="%"?"pt":esc(unit)} · Tendance ${delta===null?"—":`${delta>0?"+":""}${delta}`}</p>${lineChart(series,`${title} · ${contextLabel}`,unit)}<p class="source-label">${esc(series.source||"Source à qualifier")} · dernière période ${esc(series.labels?.at(-1)||"inconnue")}</p><div class="row-actions">${state.role!=="dg"?`<button class="btn secondary small" data-kpi-action="${code}" data-kpi-label="${esc(title)}">Créer une action sur cet écart</button>`:""}<button class="btn ghost small" data-kpi-records="${code}">${linked} action(s) liée(s)</button></div></article>`;
}
function renderPilotage() {
  const group=state.site==="group",selected=group?state.pilotSite:state.site,decisions=scoped(data.decisions).filter(d=>d.status!=="Clos"),critical=scoped(data.signals).filter(s=>s.severity==="Critique"&&isOpenSignal(s));
  return `${pageHead(group?"Pilotage Groupe":"Pilotage Site",group?"Risques, tendances et décisions":`Pilotage de ${site().name}`,"Choisir le périmètre, comprendre l’écart et ouvrir la suite utile.")}<div class="panel pilot-controls">${group?`<label>Site observé<select id="pilotSite">${OPERATIONAL_SITES.map(s=>`<option value="${s.id}" ${s.id===selected?"selected":""}>${esc(s.name)}</option>`).join("")}</select></label>`:""}<label>Historique affiché<select id="pilotPeriod">${[["all","Tout l’historique disponible"],["4","4 derniers relevés"],["8","8 derniers relevés"]].map(([value,label])=>`<option value="${value}" ${value===state.period?"selected":""}>${label}</option>`).join("")}</select></label><span class="hint">${esc(getSiteName(selected))} · chaque courbe conserve sa source</span></div>${group?'<p class="alert">Pas de moyenne Groupe des pourcentages : les définitions, périmètres et pondérations doivent être validés.</p>':""}<div class="grid cols-2 section">${[["trs","TRS","high","%"],["scrap","Qualité · Rebut","low","%"],["safety_signal","Sécurité","low",""],["service","Service client","high","%"],["staffing","Personnel","high","%"]].map(([code,title,direction,unit])=>pilotageChart(indicatorSeries(selected,code),{code,title,direction,unit,contextLabel:getSiteName(selected)})).join("")}</div><section class="section"><div class="section-title"><h2>Décisions et alertes · ${esc(site().name)}</h2><button class="btn secondary" data-new-decision>＋ Décision / escalade</button></div><div class="list">${decisions.map(d=>`<article class="row"><div><b>${esc(d.title)}</b><p class="hint">${esc(getSiteName(d.site_id))} · ${esc(d.owner)} · ${shortDate(d.due_date)}</p></div>${recordLink(d.id,"Décider")}</article>`).join("")}${critical.map(s=>`<article class="row"><div>${pill("Critique","critical")}<b>${esc(s.description)}</b></div>${recordLink(s.id,"Ouvrir")}</article>`).join("")}${!decisions.length&&!critical.length?empty("Aucune décision ouverte ni signal critique sur ce périmètre."):""}</div></section>${group?`<section class="section panel"><h2>Couverture des six entités</h2><div class="table-wrap"><table class="data-table"><thead><tr><th>Entité</th><th>Sources d’historique</th><th>Actions ouvertes</th><th></th></tr></thead><tbody>${OPERATIONAL_SITES.map(s=>`<tr><td>${esc(s.name)}</td><td>${data.trends.filter(t=>t.site_id===s.id&&t.values?.some(Number.isFinite)).length||"À connecter"}</td><td>${data.actions.filter(a=>a.site_id===s.id&&isOpenAction(a)).length}</td><td><button class="btn secondary small" data-set-site="${s.id}">Ouvrir le site</button></td></tr>`).join("")}</tbody></table></div></section>`:""}`;
}
function validateImport(incoming) {
  if(incoming?.meta?.schema!==6)throw new Error("Format de sauvegarde incompatible.");
  for(const key of ["signals","actions","problems","documents"])if(!Array.isArray(incoming[key]))throw new Error(`Collection manquante : ${key}`);
  const normalized=upgradeData(incoming),sites=new Set(SITES.map(s=>s.id));
  for(const [key,rows] of Object.entries(normalized).filter(([,v])=>Array.isArray(v))) {const ids=new Set();for(const row of rows){if(!row||typeof row!=="object"||Array.isArray(row))throw new Error(`Entrée invalide : ${key}`);if(row.id){if(ids.has(row.id))throw new Error(`Identifiant dupliqué : ${row.id}`);ids.add(row.id);}if(row.site_id&&!sites.has(row.site_id))throw new Error(`Site inconnu dans ${key}`);}}
  for(const p of normalized.problems)if(!DOCUMENT_SCHEMAS[p.method])throw new Error("Méthode de problème inconnue.");
  return normalized;
}
function importData(event) {
  const file=event.target.files?.[0];if(!file)return;if(state.role!=="lean")return toast("L’import complet est réservé au Responsable Lean Groupe.");
  const reader=new FileReader();reader.onerror=()=>toast("Fichier illisible.");reader.onload=()=>{try{const incoming=validateImport(JSON.parse(reader.result));modal("Restaurer une sauvegarde",`<p>Le fichier contient ${incoming.documents.length} documents, ${incoming.actions.length} actions et ${incoming.gembas.length} Gembas. Il remplacera les données locales de cet appareil.</p><p>Une copie des données actuelles sera conservée et téléchargeable dans Compte.</p><div class="form-actions"><button class="btn" id="confirmImport">Restaurer cette sauvegarde</button><button class="btn secondary" data-close-modal>Annuler</button></div>`);$("confirmImport").onclick=()=>{const previous=clone(data);try{localStorage.setItem(`${STORAGE_KEY}-before-import`,JSON.stringify(previous));data=incoming;const priorConflict=storageConflict;storageConflict=false;if(!save()){data=previous;storageConflict=priorConflict;return;}window.biaUnreadable=false;closeModal();render();toast("Sauvegarde restaurée. La version précédente est conservée dans Compte.");}catch{data=previous;toast("Import annulé : espace local insuffisant.");}};}catch(error){toast(`Import refusé : ${error.message}`);}};reader.readAsText(file);
}
function bindDashboards() {
  document.querySelectorAll("[data-export-previous]").forEach(b=>b.onclick=()=>{const raw=localStorage.getItem(`${STORAGE_KEY}-before-import`);if(!raw)return;const url=URL.createObjectURL(new Blob([raw],{type:"application/json"})),a=document.createElement("a");a.href=url;a.download=`bia-avant-import-${today()}.json`;a.click();URL.revokeObjectURL(url);});
  $("pilotSite")?.addEventListener("change",e=>{state.pilotSite=e.target.value;render();});
  $("pilotPeriod")?.addEventListener("change",e=>{state.period=e.target.value;render();});
  document.querySelectorAll("[data-topic-axis]").forEach(b=>b.onclick=()=>topicForm(null,{axis:b.dataset.topicAxis,title:b.dataset.topicTitle}));
  document.querySelectorAll("[data-timer]").forEach(b=>b.onclick=()=>{state.timerStarted=state.timerStarted?null:Date.now();clearInterval(window.biaTimer);render();if(state.timerStarted)window.biaTimer=setInterval(()=>{if($("meetingTimer"))$("meetingTimer").textContent=timerLabel();},1000);});
}
