"use strict";

function gembaObservations(g) {
  return g.observations|| (g.finding?[{id:`${g.id}-01`,fact:g.finding,category:g.category||"Autre",decision:"À décider",standard:"",gap:"",operator:""}]:[]);
}
function gembaStatus(g) {
  if(g.status==="Clos")return "Clos";
  if(!g.visited_at)return "Brouillon";
  return gembaOpenLinks(g).length?"Actions en cours":"À vérifier";
}
function gembaOpenLinks(g) {
  const ids=[...new Set([...gembaObservations(g).flatMap(o=>[o.action_id,o.signal_id,o.problem_id]),...linkedActions(g.id).map(a=>a.id)].filter(Boolean))];
  return ids.map(recordMeta).filter(Boolean).filter(({row,key})=>key==="actions"?isOpenAction(row):key==="signals"?isOpenSignal(row):row.status!=="Clos");
}
function gembaNext(g) {
  if(g.status==="Clos")return "Résultat vérifié";
  if(!gembaObservations(g).length)return "Ajouter la première observation";
  if(gembaObservations(g).some(o=>!o.decision||o.decision==="À décider"))return "Décider de la suite des constats";
  if(!g.visited_at)return "Terminer la visite";
  return gembaOpenLinks(g).length?"Suivre les engagements ouverts":"Revenir vérifier sur le terrain";
}
function renderGembaList() {
  const rows=scoped(data.gembas).sort((a,b)=>String(b.updated_at||b.created_at).localeCompare(String(a.updated_at||a.created_at))),open=rows.filter(g=>g.status!=="Clos"),late=open.filter(g=>g.review_date&&g.review_date<today());
  return `<div class="process-guide"><div><b>1. Préparer</b><span>Lieu et question</span></div><div><b>2. Observer</b><span>Faits et parole de l’équipe</span></div><div><b>3. Décider</b><span>Une suite par constat</span></div><div><b>4. Revenir</b><span>Vérifier le résultat</span></div></div><div class="attention-strip section"><div><b>${open.length} visite(s) à poursuivre · ${late.length} retour(s) terrain en retard</b><span>Observer le travail avec l’équipe ; questionner les faits.</span></div></div>${listSearch("Rechercher un Gemba")}<section class="section"><h2>Mes Gembas</h2><div class="list">${rows.map(g=>`<article class="row" data-search-row><div class="row-top"><div><span class="eyebrow">${esc(g.id)} · ${esc(getSiteName(g.site_id))}</span><h3>${esc(g.zone||"Périmètre à préciser")}</h3></div>${pill(gembaStatus(g),g.status==="Clos"?"done":"progress")}</div><p>${esc(g.objective||g.finding||"Observation terrain")}</p><p class="hint">${esc(g.author)} · ${gembaObservations(g).length} constat(s) · retour ${shortDate(g.review_date)}</p><div class="row-top"><b>${esc(gembaNext(g))}</b>${recordLink(g.id,g.status==="Clos"?"Consulter":"Continuer")}</div></article>`).join("")||empty("Aucune visite. Commencez par une zone et une question à comprendre.")}</div></section>`;
}
function gembaForm(existing=null) {
  const siteId=existing?.site_id||(state.site==="group"?"marzin":state.site);
  modal(existing?`${existing.id} · Préparer la visite`:"Préparer un Gemba",`<form id="gembaForm"><div class="form-grid"><label>Site<select id="gembaSite" ${existing?"disabled":""}>${siteOptions(siteId)}</select></label><label>Zone / poste / processus<input id="gembaZone" required value="${esc(existing?.zone||"")}" placeholder="Ex. préparation avant collage"></label><label class="wide">Que voulons-nous comprendre ?<input id="gembaObjective" required value="${esc(existing?.objective||"")}" placeholder="Ex. Pourquoi les pièces attendent-elles avant contrôle ?"></label><label>Animateur de la visite<input id="gembaAuthor" required value="${esc(existing?.author||"")}"></label><label>Date de retour prévue<input type="date" id="gembaReview" value="${existing?.review_date||""}"></label></div><p class="hint">Sur le terrain : demandez à l’opérateur ce qui l’aide et ce qui l’empêche de bien travailler.</p><div class="form-actions"><button class="btn">${existing?"Enregistrer":"Commencer la visite"}</button><button type="button" class="btn secondary" data-close-modal>Annuler</button></div></form>`);
  $("gembaForm").onsubmit=e=>{e.preventDefault();const payload={...existing,id:existing?.id||nextId("G",data.gembas),site_id:$("gembaSite").value,zone:$("gembaZone").value.trim(),objective:$("gembaObjective").value.trim(),author:$("gembaAuthor").value.trim(),review_date:$("gembaReview").value||null,status:existing?.status||"Brouillon",observations:existing?gembaObservations(existing):[],created_at:existing?.created_at||now(),updated_at:now()};if(!payload.zone||!payload.objective||!payload.author||!allowedSite(payload.site_id,true))return toast("Précisez le lieu, la question et l’animateur.");if(!commitData(()=>{const g=data.gembas.find(x=>x.id===payload.id);if(g)Object.assign(g,payload);else data.gembas.unshift(payload);} ))return;closeModal();state.site=payload.site_id;state.view="terrain";state.terrainTab="gemba";receipt(payload.id,"Terrain → Gemba",payload.site_id,"Ajouter un constat");render();openGemba(payload.id);};
}
function openGemba(id) {
  const g=data.gembas.find(x=>x.id===id);if(!g||!allowedSite(g.site_id))return;
  const observations=gembaObservations(g),writable=allowedSite(g.site_id,true)&&g.status!=="Clos";
  modal(`${g.id} · Gemba · ${g.zone}`,`<div class="gemba-sheet"><div class="document-toolbar"><div><p class="eyebrow">${esc(getSiteName(g.site_id))} · ${shortDate(g.created_at)}</p><h3>${esc(g.objective||"Observation terrain")}</h3><p>${esc(g.author)} · Retour prévu : ${shortDate(g.review_date)}</p></div>${pill(gembaStatus(g),g.status==="Clos"?"done":"progress")}</div><div class="next-step"><span>PROCHAINE ÉTAPE</span><b>${esc(gembaNext(g))}</b></div><section class="section"><div class="section-title"><h3>Constats de la visite</h3>${writable?`<button class="btn" data-gemba-observe="${g.id}">＋ Ajouter un constat</button>`:""}</div><div class="list">${observations.map((o,i)=>`<article class="panel"><div class="row-top"><b>${i+1}. ${esc(o.category||"Observation")}</b>${pill(o.decision||"À décider",o.decision==="Conforme"?"done":"progress")}</div><h3>${esc(o.fact)}</h3>${photoImage(o.photo)}${o.standard?`<p><b>Attendu :</b> ${esc(o.standard)}</p>`:""}${o.gap?`<p><b>Écart :</b> ${esc(o.gap)}</p>`:""}${o.operator?`<p><b>Parole de l’équipe :</b> ${esc(o.operator)}</p>`:""}${o.hypothesis?`<p class="hint"><b>Hypothèse à vérifier :</b> ${esc(o.hypothesis)}</p>`:""}<div class="row-actions">${recordLink(o.action_id,"Action")}${recordLink(o.signal_id,"Signal")}${recordLink(o.problem_id,"Problème")}${writable?`<button class="btn secondary small" data-gemba-observe="${g.id}" data-observation="${o.id}">${o.decision==="À décider"?"Décider de la suite":"Modifier le constat"}</button>`:""}</div></article>`).join("")||empty("Notez un fait observé, puis choisissez la suite utile.")}</div></section>${relatedPanel(g.id)}${g.verification?`<section class="verification-box section"><h3>Retour terrain · ${esc(g.verification.result)}</h3><p>${esc(g.verification.evidence)}</p><p class="hint">${esc(g.verification.by)} · ${shortDate(g.verification.date)}</p></section>`:""}${historyView(g)}<div class="form-actions">${writable?`${!g.visited_at?`<button class="btn" data-gemba-finish="${g.id}">Terminer la visite</button>`:`<button class="btn" data-gemba-verify="${g.id}">Vérifier sur le terrain</button>`}<button class="btn secondary" data-gemba-edit="${g.id}">Lieu et retour prévu</button>`:""}<button class="btn ghost" data-print>Imprimer / PDF</button><button class="btn secondary" data-close-modal>Retour aux Gembas</button></div></div>`);
}
function applyGembaDecision(g,observation) {
  if([observation.action_id,observation.signal_id,observation.problem_id].some(Boolean))return;
  const base={site_id:g.site_id,origin_id:g.id,observation_id:observation.id,created_at:now(),updated_at:now()};
  if(observation.decision==="Action"){
    const a={...base,id:nextId("A",data.actions),title:observation.next_action||observation.fact,owner:observation.owner,priority:observation.category==="Sécurité"?"Haute":"Normale",status:"Ouverte",due_date:observation.due_date,origin_type:"Gemba",description:[observation.fact,observation.gap,observation.operator].filter(Boolean).join("\n"),effectiveness:null};data.actions.unshift(a);observation.action_id=a.id;
  }else if(observation.decision==="Signal"){
    const s={...base,id:nextId("S",data.signals),zone:g.zone,type:observation.category,description:observation.fact,severity:"À qualifier",state:"Nouveau",immediate_action:observation.next_action||"",photo:observation.photo||"",author:g.author};data.signals.unshift(s);observation.signal_id=s.id;
  }else if(["A3","8D","QRQC"].includes(observation.decision)){
    const {problem}=createProblemRecord({...base,title:observation.fact,method:observation.decision,owner:observation.owner,context:[observation.fact,observation.gap,observation.operator].filter(Boolean).join("\n")});observation.problem_id=problem.id;
  }
}
function gembaObservationForm(id,observationId=null) {
  const g=data.gembas.find(x=>x.id===id);if(!g||!allowedSite(g.site_id,true)||g.status==="Clos")return;
  const old=gembaObservations(g).find(o=>o.id===observationId),locked=old&&(old.action_id||old.signal_id||old.problem_id),types=["À décider","Conforme","Action","Signal",...(role().nav.includes("resolution")?["A3","8D","QRQC"]:[])];
  modal(`${id} · ${old?"Compléter le constat":"Ajouter un constat"}`,`<form id="observationForm"><p class="hint">${esc(g.zone)} · ${esc(getSiteName(g.site_id))}</p><label class="field">Quel fait observez-vous ?<textarea id="observationFact" rows="3" required placeholder="Ce que vous voyez ou mesurez, sans supposer la cause">${esc(old?.fact||"")}</textarea></label><div class="form-grid section"><label>Catégorie<select id="observationCategory">${SIGNAL_TYPES.map(x=>`<option ${x===(old?.category||"Production")?"selected":""}>${x}</option>`).join("")}</select></label><label>Photo facultative<input type="file" id="observationPhoto" accept="image/jpeg,image/png,image/webp"></label><div class="wide" id="observationPreview">${photoImage(old?.photo)}</div></div><details class="section" ${old?.standard||old?.gap||old?.operator?"open":""}><summary>Comprendre avec l’équipe</summary><div class="form-grid section"><label>Standard / situation attendue<textarea id="observationStandard" rows="2">${esc(old?.standard||"")}</textarea></label><label>Écart constaté<textarea id="observationGap" rows="2">${esc(old?.gap||"")}</textarea></label><label class="wide">Que dit l’opérateur ?<textarea id="observationOperator" rows="2" placeholder="Ce qui aide ou empêche de bien travailler">${esc(old?.operator||"")}</textarea></label><label class="wide">Hypothèse à vérifier (facultatif)<input id="observationHypothesis" value="${esc(old?.hypothesis||"")}"></label></div></details><section class="verification-box section"><h3>Quelle suite utile ?</h3><label class="field">Décision<select id="observationDecision" ${locked?"disabled":""}>${types.map(x=>`<option ${x===(old?.decision||"À décider")?"selected":""}>${x}</option>`).join("")}</select></label><p class="hint">Conforme : conserver le constat. Action : amélioration simple. Signal : anomalie à qualifier. A3 / 8D / QRQC : problème à analyser.</p><div id="observationFollowup" class="form-grid"><label class="wide">Action immédiate ou engagement<textarea id="observationAction" rows="2">${esc(old?.next_action||"")}</textarea></label><label>Responsable<input id="observationOwner" value="${esc(old?.owner||"")}"></label><label>Échéance<input type="date" id="observationDue" value="${old?.due_date||""}"></label></div>${locked?`<p class="hint">Le dossier lié conserve son suivi dans son module.</p>${recordLink(locked)}`:""}</section><div class="form-actions"><button class="btn">Enregistrer le constat${locked?"":" et sa suite"}</button><button type="button" class="btn secondary" data-close-modal>Annuler</button></div></form>`);
  const photo=photoPicker("observationPhoto","observationPreview",old?.photo);const follow=()=>{$("observationFollowup").hidden=locked||["À décider","Conforme"].includes($("observationDecision").value);};$("observationDecision").onchange=follow;follow();
  $("observationForm").onsubmit=e=>{e.preventDefault();if(photo.busy||photo.error)return toast("La photo doit être prête avant l’enregistrement.");const obs={...old,id:old?.id||uid("OBS"),fact:$("observationFact").value.trim(),category:$("observationCategory").value,standard:$("observationStandard").value.trim(),gap:$("observationGap").value.trim(),operator:$("observationOperator").value.trim(),hypothesis:$("observationHypothesis").value.trim(),photo:photo.value,decision:$("observationDecision").value,next_action:$("observationAction").value.trim(),owner:$("observationOwner").value.trim(),due_date:$("observationDue").value||null};if(!obs.fact)return toast("Décrivez le fait observé.");if(!locked&&["Action","A3","8D","QRQC"].includes(obs.decision)&&(!obs.owner||obs.decision==="Action"&&(!obs.due_date||!obs.next_action)))return toast("Précisez le responsable et, pour une action, l’engagement et l’échéance.");if(!commitData(()=>{const row=data.gembas.find(x=>x.id===id);row.observations=gembaObservations(row);applyGembaDecision(row,obs);const index=row.observations.findIndex(o=>o.id===obs.id);if(index>=0)row.observations[index]=obs;else row.observations.push(obs);recordHistory(row,"Constat enregistré",obs.fact);}))return;closeModal();receipt(id,"Terrain → Gemba",g.site_id,"Constat enregistré et suite reliée");render();openGemba(id);};
}
function finishGemba(id) {
  const g=data.gembas.find(x=>x.id===id),obs=g&&gembaObservations(g);if(!g||!allowedSite(g.site_id,true))return;
  if(!obs.length||obs.some(o=>!o.decision||o.decision==="À décider"))return toast("Ajoutez un constat et choisissez une suite pour chacun avant de terminer la visite.");
  if(!commitData(()=>{const row=data.gembas.find(x=>x.id===id);row.visited_at=now();recordHistory(row,"Visite terminée");}))return;closeModal();render();openGemba(id);
}
function verifyGemba(id) {
  const g=data.gembas.find(x=>x.id===id);if(!g||!allowedSite(g.site_id,true))return;const remaining=gembaOpenLinks(g);
  modal(`${id} · Retour terrain`,`<form id="gembaVerify"><p>Revenez au poste et vérifiez avec l’équipe ce qui a changé.</p>${remaining.length?`<div class="alert">${remaining.length} dossier(s) encore ouvert(s). Le constat de retour peut être enregistré ; la clôture attendra leur traitement.</div>`:""}<div class="form-grid section"><label>Résultat<select id="gembaResult"><option>À poursuivre</option><option>Inefficace</option><option>Efficace</option></select></label><label>Vérifié par<input id="gembaVerifier" required></label><label>Date du retour<input type="date" id="gembaVerifiedAt" value="${today()}" required></label><label>Prochain retour (si nécessaire)<input type="date" id="gembaNextReview"></label><label class="wide">Que constatez-vous, avec quelle preuve ?<textarea id="gembaEvidence" required rows="3"></textarea></label></div><div class="form-actions"><button class="btn">Enregistrer la vérification</button><button type="button" class="btn secondary" data-close-modal>Annuler</button></div></form>`);
  $("gembaVerify").onsubmit=e=>{e.preventDefault();const result=$("gembaResult").value,by=$("gembaVerifier").value.trim(),date=$("gembaVerifiedAt").value,evidence=$("gembaEvidence").value.trim(),review=$("gembaNextReview").value;if(!by||!date||date>today()||!evidence)return toast("Précisez le résultat, le vérificateur et une date passée ou du jour.");if(result!=="Efficace"&&!review)return toast("Planifiez le prochain retour terrain.");if(!commitData(()=>{const row=data.gembas.find(x=>x.id===id);row.verification={result,by,date,evidence};row.review_date=review||null;row.status=result==="Efficace"&&!gembaOpenLinks(row).length?"Clos":"Actions en cours";recordHistory(row,row.status,evidence);} ))return;closeModal();receipt(id,"Terrain → Gemba",g.site_id,data.gembas.find(x=>x.id===id).status);render();openGemba(id);};
}

function auditForm(existing=null,requestedDomain=null) {
  if(existing&&!allowedSite(existing.site_id))return;
  if(existing?.status==="Terminé")return auditReport(existing);
  let draft=clone(existing||{id:null,site_id:state.site==="group"?"marzin":state.site,type:"Audit Terrain BIA",scope:"",owner:"",performed_at:today(),audit_data:{criteria:[],auditor:"",summary:""}});
  const domains=Object.entries(AUDIT_CRITERIA),index=Math.max(0,Math.min(9,requestedDomain??draft.current_domain??0)),[domain,criteria]=domains[index],saved=new Map(draft.audit_data.criteria.map(c=>[c.domain+"|"+c.criterion,c]));
  const count=draft.audit_data.criteria.filter(c=>c.score!==null&&c.score!==undefined&&c.proof?.trim()).length;
  modal(`${draft.id||"Nouvel audit"} · Audit Terrain · 50 critères`,`<form id="auditForm"><div class="form-grid"><label>Site<select id="auditSite" ${draft.id?"disabled":""}>${siteOptions(draft.site_id)}</select></label><label>Périmètre<input id="auditScope" value="${esc(draft.scope)}" required placeholder="Atelier / zone / processus"></label><label>Responsable du périmètre<input id="auditOwner" value="${esc(draft.owner)}" required></label><label>Auditeur<input id="auditAuditor" value="${esc(draft.audit_data.auditor)}" required></label><label>Date<input type="date" id="auditDate" value="${draft.performed_at}" required></label></div><div class="wizard-position section">DOMAINE ${index+1} / 10 · ${count} / 50 critères renseignés</div><div class="domain-picker">${domains.map(([name],i)=>`<button type="button" class="chip ${i===index?"active":""}" data-audit-domain="${i}" aria-label="Domaine ${i+1} : ${esc(name)}">${i+1}. ${esc(name)}</button>`).join("")}</div><p class="hint">0 : absent · 1 : ponctuel · 2 : partiel · 3 : appliqué · 4 : maîtrisé · 5 : durable et amélioré. Une absence constatée constitue une preuve.</p><fieldset class="audit-fieldset"><legend>${esc(domain)}</legend>${criteria.map((criterion,ci)=>{const c=saved.get(domain+"|"+criterion)||{};return `<div class="audit-criterion"><b>${index+1}.${ci+1} ${esc(criterion)}</b><label>Note<select data-audit-score data-criterion="${esc(criterion)}"><option value="">À noter</option>${[0,1,2,3,4,5].map(n=>`<option value="${n}" ${c.score===n?"selected":""}>${n}/5</option>`).join("")}</select></label><label>Preuve / observation<textarea data-audit-proof rows="2" placeholder="Fait observé ou document consulté">${esc(c.proof||"")}</textarea></label></div>`;}).join("")}</fieldset>${index===9?`<label class="field">Synthèse et priorité<textarea id="auditSummary" rows="3">${esc(draft.audit_data.summary||"")}</textarea></label><label class="check section"><input id="auditAction" type="checkbox" checked> Créer une action par domaine inférieur à 3/5</label>`:""}<p class="save-state" id="saveState" role="status">Brouillon sauvegardé automatiquement pendant la saisie</p><div class="wizard-actions"><button type="button" class="btn secondary" data-audit-domain="${index-1}" ${index===0?"disabled":""}>← Précédent</button><button type="button" class="btn ghost" id="saveAuditDraft">Enregistrer et quitter</button>${index<9?`<button type="button" class="btn" data-audit-domain="${index+1}">Continuer →</button>`:'<button class="btn">Terminer l’audit</button>'}</div></form>`);
  const capture=()=>{draft.site_id=$("auditSite").value;draft.scope=$("auditScope").value.trim();draft.owner=$("auditOwner").value.trim();draft.performed_at=$("auditDate").value;draft.audit_data.auditor=$("auditAuditor").value.trim();if($("auditSummary"))draft.audit_data.summary=$("auditSummary").value.trim();const scores=[...document.querySelectorAll("[data-audit-score]")],proofs=[...document.querySelectorAll("[data-audit-proof]")];const rest=draft.audit_data.criteria.filter(c=>c.domain!==domain);draft.audit_data.criteria=[...rest,...scores.map((input,i)=>({domain,criterion:input.dataset.criterion,score:input.value===""?null:Number(input.value),proof:proofs[i].value.trim()}))];draft.current_domain=index;};
  const persist=(complete=false)=>{capture();if(!allowedSite(draft.site_id,true))return false;const scored=draft.audit_data.criteria;if(complete&&(!draft.scope||!draft.owner||!draft.audit_data.auditor||!draft.performed_at||draft.performed_at>today()||scored.length!==50||scored.some(c=>c.score===null||!c.proof)))return toast("Complétez les 50 notes et preuves, le périmètre, les responsables et la date."),false;
    draft.id ||= nextId("AUD",data.audits);draft.status=complete?"Terminé":"Brouillon";draft.score=complete?Math.round(scored.reduce((sum,c)=>sum+c.score,0)/250*100):null;draft.updated_at=now();draft.audit_data.proof_count=scored.filter(c=>c.proof).length;draft.audit_data.domain_scores=complete?Object.fromEntries(domains.map(([name])=>[name,scored.filter(c=>c.domain===name).reduce((sum,c)=>sum+c.score,0)/5])):null;
    return commitData(()=>{const found=data.audits.find(a=>a.id===draft.id);if(found)Object.assign(found,clone(draft));else data.audits.unshift(clone(draft));if(complete&&$("auditAction")?.checked)for(const [name,value] of Object.entries(draft.audit_data.domain_scores)){if(value>=3||data.actions.some(a=>a.origin_id===draft.id&&a.audit_domain===name))continue;data.actions.unshift({id:nextId("A",data.actions),site_id:draft.site_id,title:`Traiter l’écart · ${name}`,description:scored.filter(c=>c.domain===name&&c.score<3).map(c=>`${c.criterion} : ${c.proof}`).join("\n"),owner:draft.owner,priority:value<2?"Haute":"Normale",status:"Ouverte",due_date:null,origin_type:"Audit",origin_id:draft.id,audit_domain:name,created_at:now()});}});
  };
  setModalSaver(()=>modalDirty||draft.id?persist(false):true);
  document.querySelectorAll("[data-audit-domain]").forEach(b=>b.onclick=()=>{if(persist(false)){modalSaver=null;auditForm(data.audits.find(a=>a.id===draft.id),Number(b.dataset.auditDomain));}});
  $("saveAuditDraft").onclick=()=>{if(!persist(false))return;closeModal();state.site=draft.site_id;state.view="audits";receipt(draft.id,"Audits",draft.site_id,`Reprendre au domaine ${index+1}`);render();};
  $("auditForm").onsubmit=e=>{e.preventDefault();if(!persist(true))return;closeModal();receipt(draft.id,"Audits",draft.site_id,"Consulter le résultat et attribuer les échéances des actions");render();auditReport(data.audits.find(a=>a.id===draft.id));};
}
function auditReport(a) {
  modal(`${a.id} · Résultat de l’audit`,`<article class="audit-report"><p class="eyebrow">${esc(getSiteName(a.site_id))} · ${shortDate(a.performed_at)}</p><h3>${esc(a.scope)} · ${a.score??"—"}/100</h3><p>${esc(a.audit_data?.summary||a.proof||"Synthèse non renseignée")}</p>${a.audit_data?.criteria?.length?Object.keys(AUDIT_CRITERIA).map(domain=>`<section class="panel section"><h3>${esc(domain)}</h3>${a.audit_data.criteria.filter(c=>c.domain===domain).map(c=>`<p><b>${c.score??"—"}/5 · ${esc(c.criterion)}</b><br>${esc(c.proof)}</p>`).join("")}</section>`).join(""):empty("Ancien résultat conservé : les 50 critères détaillés n’étaient pas enregistrés.")}${relatedPanel(a.id)}<div class="form-actions"><button class="btn secondary" data-print>Imprimer / PDF</button><button class="btn secondary" data-close-modal>Fermer</button></div></article>`);
}
function bindFieldwork() {
  document.querySelectorAll("[data-gemba-observe]").forEach(b=>b.onclick=()=>gembaObservationForm(b.dataset.gembaObserve,b.dataset.observation));
  document.querySelectorAll("[data-gemba-finish]").forEach(b=>b.onclick=()=>finishGemba(b.dataset.gembaFinish));
  document.querySelectorAll("[data-gemba-verify]").forEach(b=>b.onclick=()=>verifyGemba(b.dataset.gembaVerify));
  document.querySelectorAll("[data-gemba-edit]").forEach(b=>b.onclick=()=>gembaForm(data.gembas.find(g=>g.id===b.dataset.gembaEdit)));
}
