"use strict";

/* Bibliothèque V5.1 : contenus génériques, sans donnée BIA supposée.
   Le Plan des 100 premiers jours est volontairement absent. */
const LEAN_ROUTES=[
  ["unknown","Je ne sais pas ce qui ne va pas","Diagnostic industriel 360°","Observer un cycle complet, relever les écarts et établir un Pareto."],
  ["stocks","Trop de stocks ou d’encours","VSM et flux","Compter l’encours à chaque étape et mesurer le temps de traversée."],
  ["changeover","Changements de série trop longs","Kit chantier SMED","Filmer du dernier produit bon au premier produit bon stable."],
  ["breakdowns","Pannes répétitives","TPM et maintenance","Construire le Pareto des heures perdues et vérifier MTBF/MTTR."],
  ["defects","Défauts ou retouches","Résolution de problèmes","Sécuriser le client puis stratifier les défauts par produit, moyen et équipe."],
  ["late","Livraisons en retard","VSM et flux","Reconstituer la chronologie factuelle de trois commandes en retard."],
  ["low-oee","TRS trop faible","Référentiel KPI industriels","Valider temps requis, codes d’arrêt, vitesse et qualité avant d’agir."],
  ["disorder","Poste désorganisé","5S utile et maintenu","Photographier la référence et mesurer recherches, risques et déplacements."],
  ["capacity","Capacité insuffisante","Identifier et exploiter un goulot","Comparer demande, capacité démontrée et files par étape."],
  ["supply","Ruptures d’approvisionnement","Flux tiré et Kanban","Classer les ruptures : fournisseur, donnée, consommation ou manutention."],
  ["site-gap","Écart entre deux sites","Benchmark contextualisé","Aligner définitions, mix, technologies et périmètres avant toute comparaison."],
  ["new-line","Industrialiser une nouvelle ligne","Industrialisation robuste","Figer demande, capacité, ergonomie, qualité et critères d’acceptation."],
  ["no-data","Données peu fiables","Plan de mesure terrain","Mesurer un petit échantillon fiable avant toute automatisation."],
  ["resistance","Équipes réticentes","Conduite du changement terrain","Traiter un irritant reconnu et obtenir rapidement un résultat visible."]
];

const LEAN_MODULES=[
  {id:"start",no:"00.01",title:"START HERE",category:"Démarrage",objective:"Choisir la démarche minimale à partir d’un problème réel.",when:"Toute nouvelle demande ou dérive.",steps:["Formuler l’écart","Aller voir","Mesurer simplement","Tester une cause","Essayer une contre-mesure","Vérifier puis standardiser"],checklist:["Périmètre et période","Propriétaire identifié","Observation planifiée","Résultat attendu"],deliverables:["Route vers l’outil","Première action terrain"],pitfalls:["Choisir l’outil avant le problème","Lancer trop de sujets"]},
  {id:"audit-terrain",no:"01.01",title:"Audit Terrain BIA",category:"Diagnostic",objective:"Évaluer dix domaines avec cinquante critères et des preuves.",when:"Audit site, atelier ou processus.",steps:["Cadrer le périmètre","Observer au poste","Noter chaque critère 0 à 5","Joindre une preuve","Créer les actions utiles","Restituer les priorités"],checklist:["50 critères parcourus","Preuve par critère","Risque immédiat sécurisé","Actions attribuées"],deliverables:["Score par domaine","Plan d’actions","Synthèse terrain"],pitfalls:["Noter sur impression","Auditer les personnes"]},
  {id:"diagnostic-360",no:"02.01",title:"Diagnostic industriel 360°",category:"Diagnostic",objective:"Produire une lecture factuelle des risques, forces et opportunités.",when:"Première revue approfondie ou dérive globale.",steps:["Cadrer avec la direction","Lire les KPI","Gemba transverse","Interroger les rôles clés","Hiérarchiser les écarts","Restituer Top 5"],checklist:["Périmètre explicite","Preuves disponibles","Écart séparé de la cause","Quick wins distincts"],deliverables:["Radar de maturité","Top risques","Priorités 90 jours"],pitfalls:["Comparer sans contexte","Promettre avant le diagnostic"]},
  {id:"gemba-60",no:"02.02",title:"Gemba en 60 minutes",category:"Diagnostic",objective:"Voir le travail réel, les flux et les pertes sans inspecter les personnes.",when:"Avant toute analyse de bureau.",steps:["Rappeler le processus attendu","Suivre le flux physique","Suivre l’information","Questionner les écarts","Reformuler les faits","Décider de la suite"],checklist:["Attentes et encours","Mouvements","Défauts","Surprocess","Compétences inexploitées"],deliverables:["Fiche Gemba","Constats classés","Décision mesurer/sécuriser/analyser"],pitfalls:["Donner la solution immédiatement","Confondre constat et jugement"]},
  {id:"lean-system",no:"03.01",title:"Lean Management System",category:"Management",objective:"Relier stratégie, SQCDP, escalade, résolution et compétences.",when:"Construction du système atelier → site → Groupe.",steps:["Définir les résultats","Installer les rituels","Régler l’escalade","Standardiser la réaction","Coacher les managers","Auditer le système"],checklist:["Rôles par niveau","Sortie attendue par rituel","Règle d’escalade","Boucle d’apprentissage"],deliverables:["Architecture N1 à N4","Calendrier des rituels","Matrice d’escalade"],pitfalls:["Empiler les réunions","Centraliser le terrain"]},
  {id:"sqcdp",no:"04.01",title:"SQCDP atelier, site et Groupe",category:"Management",objective:"Rendre visibles les écarts utiles et décider au bon niveau.",when:"Quotidien atelier, hebdomadaire site, mensuel Groupe.",steps:["Choisir les mesures","Définir cible et source","Afficher l’écart","Attribuer l’action","Escalader si nécessaire","Vérifier au rituel suivant"],checklist:["Sécurité en premier","Données datées","Réunion courte","Historique des décisions"],deliverables:["Tableau SQCDP","Règle d’escalade","TOP 15"],pitfalls:["Multiplier les KPI","Transformer en reporting"]},
  {id:"obeya",no:"04.02",title:"Obeya Groupe",category:"Management",objective:"Concentrer stratégie, performance, projets, risques et décisions.",when:"Revue Groupe et arbitrages transverses.",steps:["Afficher les priorités","Montrer les tendances","Visualiser les projets","Rendre les risques visibles","Décider","Suivre les engagements"],checklist:["Stratégie","SQCDP","Projets","Risques","Décisions","Actions"],deliverables:["Trame Obeya","Journal des décisions","Revue mensuelle"],pitfalls:["Galerie de diapositives","Décisions sans propriétaire"]},
  {id:"kpi",no:"05.01",title:"Référentiel KPI industriels",category:"Pilotage",objective:"Définir des mesures stables, comparables et liées à une décision.",when:"Avant comparaison ou automatisation.",steps:["Partir de la décision","Écrire la formule","Fixer unité et périmètre","Nommer la source","Tester au terrain","Définir la réaction"],checklist:["Numérateur/dénominateur","Période","Exclusions","Source","Propriétaire","Cible"],deliverables:["Dictionnaire KPI","Arbre Groupe/site/atelier"],pitfalls:["Moyenner des périmètres incompatibles","KPI sans réaction"]},
  {id:"decision-tree",no:"05.02",title:"J’ai un problème : quel outil ?",category:"Pilotage",objective:"Orienter vers la première observation et l’outil proportionné.",when:"Quand la démarche reste floue.",steps:["Choisir le symptôme","Observer","Mesurer l’écart","Tester une cause","Choisir l’outil minimal","Escalader si nécessaire"],checklist:["Symptôme distinct de la cause","Mesure disponible","Résultat attendu"],deliverables:["Route problème → mesure → outil"],pitfalls:["DMAIC pour tout","5S comme solution universelle"]},
  {id:"problem-solving",no:"06.01",title:"Résolution de problèmes",category:"Méthodes",objective:"Conduire A3, 8D, QRQC, PDCA, 5 Pourquoi et Ishikawa.",when:"Écart récurrent, critique ou complexe.",steps:["Sécuriser","Décrire l’écart","Stratifier","Prouver la cause","Tester la contre-mesure","Vérifier","Standardiser"],checklist:["Problème chiffré","Cause prouvée","Action sur cause","Avant/après","Contrôle de tenue"],deliverables:["A3 ou 8D","Plan d’actions","Leçon apprise"],pitfalls:["Ishikawa non vérifié","Clore à la mise en œuvre"]},
  {id:"vsm",no:"07.01",title:"VSM et flux",category:"Flux",objective:"Réduire attentes, encours et temps de traversée.",when:"Retards, WIP élevé ou flux complexe.",steps:["Choisir une famille","Relever le flux réel","Mesurer CT et stocks","Calculer VA/NVA","Dessiner le futur","Planifier les essais"],checklist:["Client/demande","Takt","CT","Encours","Information","Transferts"],deliverables:["Current State","Future State","Plan 30/60/90"],pitfalls:["Dessiner en salle","Cartographier toute l’usine"]},
  {id:"bottleneck",no:"07.02",title:"Identifier et exploiter un goulot",category:"Flux",objective:"Protéger le débit de la contrainte réelle.",when:"Files persistantes ou saturation.",steps:["Localiser la file","Mesurer débit/saturation","Exploiter sans investir","Subordonner le flux","Élever la contrainte","Recommencer"],checklist:["File avant poste","Famine après","Capacité démontrée","Aléas","Priorités"],deliverables:["Fiche contrainte","Buffer visuel","Plan d’exploitation"],pitfalls:["Optimiser chaque machine","Déplacer le goulot sans suivi"]},
  {id:"five-s",no:"08.01",title:"5S utile et maintenu",category:"Stabilité",objective:"Réduire risques, recherches et anomalies au poste.",when:"Désorganisation visible ou standard difficile.",steps:["Débarrasser","Ranger","Nettoyer pour inspecter","Standardiser visuellement","Faire tenir"],checklist:["Place nommée","Quantité définie","Accès ergonomique","Standard photo","Propriétaire"],deliverables:["Audit court","Standard photo","Plan d’action"],pitfalls:["Noter la propreté uniquement","Sanctionner l’opérateur"]},
  {id:"standard-work",no:"08.02",title:"Standard Work",category:"Stabilité",objective:"Décrire la meilleure manière connue, observable et améliorable.",when:"Variabilité, défauts, formation ou transfert.",steps:["Observer plusieurs cycles","Définir séquence et points clés","Impliquer l’opérateur","Tester","Former","Réviser"],checklist:["But","Séquence","Temps","Sécurité/qualité","Réaction à l’écart","Version"],deliverables:["Standard opératoire","Standard management","Matrice de formation"],pitfalls:["Procédure illisible","Figer une mauvaise pratique"]},
  {id:"smed",no:"09.01",title:"Kit chantier SMED",category:"Méthodes",objective:"Réduire du dernier produit bon au premier produit bon stable.",when:"Changement long, variable ou instable.",steps:["Filmer","Séparer interne/externe","Externaliser","Simplifier","Paralléliser","Tester puis standardiser"],checklist:["Début/fin définis","Tâches chronométrées","Déplacements","Réglages","Premier bon inclus"],deliverables:["Chrono détaillé","Spaghetti","Standard final","Gain vérifié"],pitfalls:["Exclure les essais qualité","Acheter avant de simplifier"]},
  {id:"tpm",no:"10.01",title:"TPM et maintenance",category:"Maintenance",objective:"Réduire les pertes selon criticité et causes dominantes.",when:"Pannes, micro-arrêts ou maintenance réactive.",steps:["Classer la criticité","Pareto des pertes","Mesurer MTBF/MTTR","Traiter les causes","Définir le préventif","Sécuriser les pièces"],checklist:["Impact sécurité/client","Secours","Pièces critiques","Compétences","Qualité GMAO"],deliverables:["Matrice criticité","Pareto","Plan maintenance"],pitfalls:["Compter seulement les pannes","TPM réservée à la maintenance"]},
  {id:"quality",no:"11.01",title:"Qualité et amélioration continue",category:"Qualité",objective:"Sécuriser le client puis supprimer création et échappement du défaut.",when:"NC, retouches, réclamations ou dérive FPY.",steps:["Contenir","Stratifier","Chercher lieu de création","Chercher non-détection","Prouver les causes","Prévenir la récidive"],checklist:["Lots concernés","Traçabilité","FPY","Cause apparition","Cause échappement"],deliverables:["QRQC/8D","Plan de contrôle","Standard robuste"],pitfalls:["Blâmer l’opérateur","Renforcer le contrôle sans traiter la cause"]},
  {id:"industrialization",no:"12.01",title:"Industrialisation robuste",category:"Industrialisation",objective:"Démontrer capacité, qualité, maintenabilité et ergonomie avant série.",when:"Nouveau produit, ligne, transfert ou montée en cadence.",steps:["Figer les hypothèses","Analyser risques process","Concevoir flux/poste","Tester capacité","Valider qualité","Organiser le ramp-up"],checklist:["Takt/CT","Capabilité","Ergonomie","Maintenance","Formation","Critères d’acceptation"],deliverables:["Dossier industrialisation","Plan de validation","Courbe ramp-up"],pitfalls:["Valider au débit instantané","Oublier les changements de série"]},
  {id:"multisite",no:"13.01",title:"Pilotage multisite et transférabilité",category:"Multisite",objective:"Déployer ce qui fonctionne sans imposer une copie aveugle.",when:"Pratique candidate au déploiement.",steps:["Prouver localement","Décrire le contexte","Évaluer transférabilité","Tester sur un second site","Adapter","Standard Groupe si pertinent"],checklist:["Résultat vérifié","Contexte source","Contraintes cibles","Pilote deuxième site","Sponsor"],deliverables:["Matrice de transférabilité","REX pilote","Décision Groupe"],pitfalls:["Copier sans contexte","Standardiser trop tôt"]},
  {id:"benchmark",no:"13.02",title:"Benchmark contextualisé des six sites",category:"Multisite",objective:"Comparer des pratiques et pertes réellement comparables.",when:"Écart apparent entre entités.",steps:["Aligner les définitions","Segmenter mix/volume/technologie","Normaliser si légitime","Observer les pratiques","Tester la pratique candidate","Mesurer le transfert"],checklist:["Même formule","Même période","Contexte documenté","Pas de classement simpliste"],deliverables:["Benchmark explicable","Pratique candidate","Plan de test"],pitfalls:["Palmarès des sites","Moyenne de ratios incompatibles"]},
  {id:"governance",no:"13.03",title:"Gouvernance Excellence Opérationnelle",category:"Multisite",objective:"Clarifier décisions, standards, coaching et arbitrages Groupe/site.",when:"Déploiement du BIA Production System.",steps:["Définir les niveaux","Nommer propriétaires","Installer les revues","Fixer règles d’escalade","Arbitrer les standards","Auditer l’efficacité"],checklist:["RACI","Calendrier","Entrées/sorties","Décisions tracées","Coaching"],deliverables:["Gouvernance N1-N4","RACI","Agenda annuel"],pitfalls:["Gouvernance sans décision","Lean centralisé"]},
  {id:"transverse",no:"14.01",title:"Faire avancer six sites sans lien hiérarchique",category:"Leadership",objective:"Créer engagement et cohérence par les faits, le service et la preuve.",when:"Animation transverse Groupe.",steps:["Clarifier le mandat","Écouter les sites","Choisir un irritant commun","Construire un pilote","Prouver le résultat","Faire porter le REX par le site"],checklist:["Sponsor","Bénéfice site","Charge réaliste","Pilote volontaire","Reconnaissance"],deliverables:["Contrat de coopération","Pilote","REX partagé"],pitfalls:["Imposer le vocabulaire","Sur-solliciter les sites"]},
  {id:"change",no:"14.02",title:"Conduite du changement terrain",category:"Leadership",objective:"Faire adopter une pratique parce qu’elle aide le travail réel.",when:"Nouveau rituel, standard ou outil numérique.",steps:["Identifier l’irritant","Co-construire","Tester petit","Mesurer l’aide réelle","Former au poste","Corriger puis étendre"],checklist:["Temps gagné","Rôle clair","Support simple","Droit au retour","Manager impliqué"],deliverables:["Plan d’adoption","Formation courte","Boucle de retour"],pitfalls:["Communication descendante seule","Déploiement big bang"]},
  {id:"ai",no:"15.01",title:"IA et excellence opérationnelle",category:"Digital",objective:"Aider analyse et préparation sans inventer les faits industriels.",when:"Synthèse, recherche de récurrence ou préparation de support.",steps:["Définir le cas d’usage","Protéger les données","Fournir les sources","Faire valider l’analyse","Tracer les décisions","Mesurer le gain"],checklist:["Données autorisées","Humain responsable","Sources visibles","Test d’erreur","Relecture métier"],deliverables:["Cas d’usage cadré","Règle de validation","Mesure du gain"],pitfalls:["Décision automatique","Données sensibles non maîtrisées"]},
  {id:"roadmap",no:"16.01",title:"Roadmap Lean 3 ans",category:"Stratégie",objective:"Séquencer stabilité, système de management et déploiement.",when:"Construction de la trajectoire Groupe.",steps:["Établir le diagnostic","Choisir les enjeux","Définir les capacités","Sélectionner les pilotes","Planifier les vagues","Réviser trimestriellement"],checklist:["Lien stratégie","Capacité des sites","Bénéfices","Risques","Jalons","Critères d’arrêt"],deliverables:["Roadmap","Portefeuille","Revue trimestrielle"],pitfalls:["Liste d’outils","Plan figé trois ans"]},
  {id:"models",no:"17.01",title:"Bibliothèque de modèles terrain",category:"Modèles",objective:"Utiliser un support proportionné, versionné et relié au registre maître.",when:"Gemba, audit, problème, action ou standard.",steps:["Choisir le modèle","Créer l’instance","Relier l’origine","Remplir au terrain","Faire valider","Réviser si nécessaire"],checklist:["Identifiant","Site/atelier","Auteur/date","Version","Liens","Statut"],deliverables:["Document remplissable","PDF imprimable","Historique"],pitfalls:["PDF vierge isolé","Données dupliquées"]},
  {id:"cases",no:"18.01",title:"15 cas industriels guidés",category:"Entraînement",objective:"S’entraîner à choisir observation, mesure et outil.",when:"Coaching des managers et animateurs.",steps:["Lire le problème","Choisir le premier Gemba","Définir la mesure","Formuler les hypothèses","Choisir l’outil","Comparer avec le corrigé"],checklist:["Pas de solution immédiate","Cause à prouver","KPI lié","Standardisation prévue"],deliverables:["Cas traité","Débrief","Plan de progrès"],pitfalls:["Chercher la bonne réponse unique","Oublier le contexte"]},
  {id:"questions",no:"18.02",title:"20 questions par interlocuteur",category:"Entretiens",objective:"Préparer des entretiens structurés sans orienter les réponses.",when:"Diagnostic site ou cadrage chantier.",steps:["Choisir le rôle","Préparer les faits connus","Poser des questions ouvertes","Demander un exemple","Recouper au terrain","Restituer sans attribution personnelle"],checklist:["Direction","Production","Qualité","Maintenance","Méthodes","Opérateurs"],deliverables:["Guide d’entretien","Faits à vérifier","Contradictions à recouper"],pitfalls:["Interrogatoire","Transformer opinion en fait"]},
  {id:"direction",no:"19.01",title:"Support Direction — démarche multisite",category:"Direction",objective:"Présenter risques, décisions, bénéfices et arbitrages sans jargon.",when:"Comité de direction ou revue Groupe.",steps:["Rappeler l’enjeu","Montrer la tendance","Expliquer les écarts","Présenter les options","Demander une décision","Tracer l’engagement"],checklist:["Une page","Sources","Décision attendue","Responsable","Échéance"],deliverables:["Synthèse Direction","Journal de décisions","Plan d’accompagnement"],pitfalls:["Catalogue d’outils","Trop de chiffres"]},
  {id:"bia-evidence",no:"20.01",title:"Registre faits, hypothèses et terrain",category:"Référentiel",objective:"Séparer ce qui est vérifié, probable et à confirmer.",when:"Toute analyse BIA ou préparation de décision.",steps:["Écrire l’information","Classer A/B/C","Identifier la source","Dater","Nommer le vérificateur","Reclasser après contrôle"],checklist:["Fait sourcé","Hypothèse explicite","Point à confirmer attribué","Date de revue"],deliverables:["Registre de preuves","Liste de vérification","Décisions fiables"],pitfalls:["Présenter une hypothèse comme un fait","Source non datée"]}
];
