/* BIA Operating System V4 — bibliothèque métier opérationnelle.
   Les contenus sont volontairement courts, orientés terrain et indépendants
   de toute donnée BIA non vérifiée. */

const TOOL_PROBLEMS = [
  {id:"unknown",problem:"Je ne sais pas ce qui ne va pas",signal:"Les résultats se dégradent sans cause évidente",observe:"Gemba transverse puis diagnostic 360°",measure:"Écarts SQCDP, stabilité, files, reprises, irritants",tools:["Gemba 60 min","Diagnostic 360°","Pareto"],first:"Choisir un périmètre et observer un cycle complet sans proposer de solution."},
  {id:"stocks",problem:"J’ai trop de stocks ou d’encours",signal:"Files, palettes et attente masquent le vrai problème",observe:"Suivre une famille produit de bout en bout",measure:"WIP, jours de stock, lead time, temps VA/NVA",tools:["VSM","Goulot","FIFO / Kanban"],first:"Compter l’encours à chaque étape et dater l’entrée des pièces."},
  {id:"changeover",problem:"Les changements de série sont trop longs",signal:"Machine arrêtée et redémarrage instable",observe:"Filmer du dernier produit bon au premier produit bon",measure:"Durée totale, tâches internes/externes, reprises",tools:["SMED","Standard Work","5 Pourquoi"],first:"Chronométrer un changement réel sans interrompre l’équipe."},
  {id:"breakdowns",problem:"J’ai des pannes répétitives",signal:"Même équipement, mêmes symptômes, mêmes urgences",observe:"Historique GMAO et conditions juste avant panne",measure:"Pareto pannes, MTBF, MTTR, pertes TRS",tools:["Pareto","TPM","5 Pourquoi / Ishikawa"],first:"Construire le Pareto des heures perdues, pas seulement du nombre de pannes."},
  {id:"defects",problem:"J’ai des défauts ou des retouches",signal:"Contrôles tardifs et corrections récurrentes",observe:"Lieu de création du défaut, pas seulement lieu de détection",measure:"FPY, PPM, scrap, rework, coût de non-qualité",tools:["Pareto","8D / A3","Poka-Yoke"],first:"Sécuriser le client puis stratifier les défauts par produit, machine et équipe."},
  {id:"late",problem:"Mes livraisons sont en retard",signal:"Priorités changeantes et ordres qui attendent",observe:"Chemin réel de la commande à l’expédition",measure:"OTD, OTIF, lead time, adhérence planning",tools:["VSM","Capacité","Goulot / équilibrage"],first:"Prendre trois commandes en retard et reconstituer leur chronologie factuelle."},
  {id:"low-oee",problem:"Le TRS est faible",signal:"Perte globale connue, pertes élémentaires mal définies",observe:"Arrêts, micro-arrêts, vitesse et défauts par créneau",measure:"Disponibilité × Performance × Qualité",tools:["Pareto pertes","TPM","SMED / Standard Work"],first:"Valider la définition du temps requis et la qualité des codes d’arrêt."},
  {id:"disorder",problem:"Le poste est désorganisé",signal:"Recherche, déplacements et risques au quotidien",observe:"Gestes, trajets, objets utilisés et zones d’attente",measure:"Temps de recherche, distance, anomalies, fréquence",tools:["5S","Standard Work","Ergonomie"],first:"Photographier l’état de référence et retirer uniquement l’inutile évident."},
  {id:"capacity",problem:"La capacité paraît insuffisante",signal:"Heures supplémentaires malgré des temps d’attente",observe:"Charge, capacité démontrée, contraintes et variabilité",measure:"Takt, temps de cycle, saturation, rendement",tools:["Goulot","Équilibrage","VSM"],first:"Comparer demande horaire, capacité démontrée et capacité théorique par étape."},
  {id:"supply",problem:"J’ai des ruptures d’approvisionnement",signal:"Production arrêtée malgré un stock global élevé",observe:"Consommation, fiabilité délais et paramètres de réappro",measure:"Ruptures, couverture, fiabilité fournisseur, exactitude stock",tools:["Pareto ruptures","Kanban","Analyse paramètres ERP"],first:"Classer les ruptures par cause réelle : fournisseur, donnée, consommation ou manutention."},
  {id:"site-gap",problem:"Deux sites ont des performances différentes",signal:"Comparaison brute sans contexte comparable",observe:"Produit, volume, mix, technologie, organisation et règles de calcul",measure:"Écart normalisé et pertes comparables",tools:["Benchmark contextualisé","Matrice transférabilité","Yokoten"],first:"Aligner d’abord les définitions et les périmètres avant de comparer les valeurs."},
  {id:"new-line",problem:"Je dois industrialiser une nouvelle ligne",signal:"Objectifs projet sans preuve de capacité au poste",observe:"Produit, flux, ergonomie, moyens, contrôle et maintenance",measure:"Capacité, capabilité, ramp-up, CT vs takt",tools:["AMDEC process","Standard Work","Plan de montée en cadence"],first:"Figer les hypothèses de demande et les critères d’acceptation du process."},
  {id:"no-data",problem:"Je manque de données fiables",signal:"Décisions fondées sur perceptions contradictoires",observe:"Source, fréquence, propriétaire et usage de chaque donnée",measure:"Complétude, exactitude, délai, cohérence",tools:["Plan de mesure","Définition KPI","Gemba"],first:"Mesurer manuellement un petit échantillon fiable avant d’automatiser."},
  {id:"resistance",problem:"Les équipes rejettent la démarche",signal:"Outils vécus comme contrôle ou charge administrative",observe:"Irritants, bénéfices attendus et décisions non expliquées",measure:"Participation, actions clôturées, irritants supprimés",tools:["Co-construction","Chantier pilote","Management quotidien"],first:"Choisir un problème reconnu par l’équipe et obtenir un résultat visible rapidement."}
];

const TOOL_MODULES = [
  {id:"start",no:"00.01",title:"START HERE",category:"Démarrage",objective:"Choisir le bon support en moins de deux minutes et commencer par le problème.",use:"À chaque nouvelle visite, demande ou écart de performance.",steps:["Nommer le problème sans citer d’outil","Aller voir le processus réel","Choisir une mesure simple et fiable","Analyser la cause avant la solution","Tester à petite échelle","Standardiser uniquement si le résultat tient"],checklist:["Le problème est formulé avec un écart, un périmètre et une période","Une observation terrain est planifiée","Un propriétaire du problème est identifié","Le résultat attendu est chiffré"],kpis:["Délai problème → première observation","Part des actions avec résultat vérifié"],deliverables:["Route vers l’outil adapté","Première action terrain"],pitfalls:["Choisir un outil avant d’avoir observé","Lancer trop de sujets en parallèle"]},
  {id:"100-days",no:"01.01",title:"Plan des 100 premiers jours",category:"Prise de poste",objective:"Comprendre, prioriser, expérimenter puis consolider sans imposer un modèle unique.",use:"Dès J0, avec une revue hebdomadaire et une synthèse mensuelle.",steps:["J0-J30 : comprendre","J31-J60 : prioriser et expérimenter","J61-J100 : consolider et commencer le déploiement"],checklist:["Sponsor et attentes clarifiés","Sept sites cartographiés","Définitions KPI alignées","Top problèmes factuels par site","Un pilote à résultat mesurable","Rituel Groupe lancé"],kpis:["Sites visités","Données fiabilisées","Quick wins vérifiés","Actions en retard","Pilotes standardisés"],deliverables:["Synthèse 1 page","Calendrier semaine par semaine","Restitution J30, J60 et J100"],pitfalls:["Promettre une solution avant le diagnostic","Comparer les sites sans contexte"],special:"hundred"},
  {id:"diagnostic-360",no:"02.01",title:"Diagnostic industriel 360°",category:"Diagnostic",objective:"Établir en une journée une lecture factuelle des risques, forces et opportunités.",use:"Première visite approfondie, revue annuelle ou dérive globale.",steps:["Cadrer avec la direction","Lire les KPI et leurs définitions","Observer le terrain","Interviewer les rôles clés","Noter les 26 domaines de 0 à 5","Restituer Top 5 problèmes et Top 5 actions"],checklist:["Périmètre explicite","Preuve associée à chaque note","Écart séparé de la cause supposée","Risques immédiats sécurisés","Quick wins distincts des chantiers structurants"],kpis:["Score moyen /5","Domaines sous 2","Risques critiques","Quick wins à 30 jours"],deliverables:["Radar de maturité","Forces/faiblesses","Top risques, opportunités et quick wins"],pitfalls:["Noter sur impression","Confondre audit de conformité et diagnostic de performance"],special:"diagnostic"},
  {id:"gemba-60",no:"02.02",title:"Gemba en 60 minutes",category:"Diagnostic",objective:"Voir le travail réel, les flux et les pertes sans transformer la visite en inspection.",use:"Avant toute analyse de bureau ou choix d’outil.",steps:["0-5 min : rappeler le processus attendu","5-20 min : suivre le flux physique","20-35 min : suivre le flux d’information","35-50 min : questionner les écarts","50-60 min : reformuler faits, impacts et suite"],checklist:["Flux physique","Flux information","Attentes et encours","Mouvements et manutention","Défauts et retouches","Surproduction et surprocess","Compétences non utilisées"],kpis:["Constats factuels","Écarts avec impact estimé","Actions évitées faute de preuve"],deliverables:["Fiche Gemba","Constats classés","Décision : mesurer, sécuriser ou analyser"],pitfalls:["Donner immédiatement la solution","Évaluer les personnes au lieu du système"],special:"gemba"},
  {id:"lean-system",no:"03.01",title:"Lean Management System",category:"Management",objective:"Relier stratégie, management quotidien, escalade, résolution de problèmes et développement des compétences.",use:"Pour construire le système atelier → site → Groupe.",steps:["Définir les quelques résultats attendus","Installer le SQCDP au plus près du travail","Escalader seulement ce qui ne peut être résolu localement","Traiter les problèmes avec un standard commun","Capitaliser les apprentissages","Auditer le système, pas la décoration"],checklist:["Rôles par niveau","Rituels avec décision attendue","Règle d’escalade","Standard de réaction","Coaching des managers","Boucle de déploiement"],kpis:["Écarts résolus au bon niveau","Délai d’escalade","Actions closes avec preuve","Standards tenus"],deliverables:["Architecture à trois niveaux","Calendrier des rituels","Matrice d’escalade"],pitfalls:["Empiler des réunions","Centraliser les décisions terrain"]},
  {id:"sqcdp",no:"04.01",title:"SQCDP atelier, site et Groupe",category:"Management",objective:"Rendre visibles les écarts utiles et décider rapidement au bon niveau.",use:"Quotidien à l’atelier, hebdomadaire au site, mensuel au Groupe.",steps:["Sélectionner 1 à 3 mesures par axe","Définir cible et rouge/vert","Afficher l’écart, pas un commentaire vague","Attribuer une action et une échéance","Escalader si ressource ou arbitrage dépasse le niveau","Vérifier le résultat au rituel suivant"],checklist:["Sécurité en premier","Données datées","Un propriétaire par indicateur","Réunion debout et courte","Pas de résolution détaillée pendant le rituel","Historique des décisions"],kpis:["Durée de réunion","Taux de présence","Actions en retard","Écarts récurrents"],deliverables:["Tableau atelier","Tableau site","Vue Groupe","Règle d’escalade"],pitfalls:["Multiplier les KPI","Faire du tableau un reporting descendant"],special:"sqcdp"},
  {id:"obeya",no:"04.02",title:"Obeya Groupe",category:"Management",objective:"Concentrer stratégie, performance, projets, risques et décisions dans une même salle de pilotage.",use:"Revue Groupe mensuelle et arbitrages transverses.",steps:["Mettre la stratégie et les priorités à gauche","Afficher SQCDP et tendances","Visualiser projets et industrialisation","Rendre visibles risques et dépendances","Décider et nommer un propriétaire","Mettre à jour le plan d’actions"],checklist:["Stratégie","Sécurité","Qualité","Service","Performance","Projets","Industrialisation","Maintenance","People","Risques","Actions"],kpis:["Décisions prises","Décisions en attente","Risques sans traitement","Bénéfices projets"],deliverables:["Trame Obeya","Ordre du jour","Journal des décisions"],pitfalls:["Faire une galerie de diapositives","Masquer les désaccords"]},
  {id:"kpi",no:"05.01",title:"Référentiel KPI industriels",category:"Pilotage",objective:"Partager des définitions stables et une hiérarchie courte de mesures utiles à la décision.",use:"Avant toute comparaison, automatisation ou revue de performance.",steps:["Partir de la décision à prendre","Définir formule, unité et périmètre","Nommer source et propriétaire","Tester la donnée au terrain","Fixer fréquence et cible","Retirer les KPI sans décision associée"],checklist:["Définition écrite","Numérateur et dénominateur","Période","Exclusions","Source","Propriétaire","Seuil et réaction"],kpis:["KPI Groupe : 6 à 10","KPI site : 8 à 15","KPI atelier : pilotables au quotidien"],deliverables:["Dictionnaire KPI","Arbre Groupe/site/atelier/chantier"],pitfalls:["Moyenner des périmètres incompatibles","Confondre indicateur de résultat et levier"],special:"kpi"},
  {id:"decision-tree",no:"05.02",title:"J’ai un problème : quel outil ?",category:"Pilotage",objective:"Orienter vers la première observation et le bon outil sans réciter le Lean.",use:"Quand le problème est connu mais la démarche reste floue.",steps:["Choisir le symptôme","Observer le flux ou le poste","Mesurer l’écart","Tester une cause","Choisir l’outil minimal","Escalader vers A3/DMAIC seulement si nécessaire"],checklist:["Symptôme distinct de la cause","Mesure disponible","Outil proportionné","Résultat attendu défini"],kpis:["Temps avant premier test","Taux de problèmes résolus sans projet lourd"],deliverables:["Route problème → observation → mesure → outil"],pitfalls:["Choisir DMAIC pour tout","Confondre 5S et solution universelle"]},
  {id:"problem-solving",no:"06.01",title:"Résolution de problèmes",category:"Méthodes",objective:"Choisir et conduire A3, PDCA, DMAIC, 8D, 5 Pourquoi, Ishikawa, Pareto ou QQOQCP.",use:"Dès qu’un écart récurrent ou complexe dépasse la réaction immédiate.",steps:["Sécuriser si nécessaire","Décrire l’écart","Mesurer et stratifier","Vérifier la cause racine","Tester la contre-mesure","Confirmer le résultat","Standardiser et partager"],checklist:["Problème chiffré","Cause prouvée","Action sur cause","Mesure avant/après","Responsable et date","Contrôle de tenue"],kpis:["Récurrence","Délai de résolution","Gain vérifié","Actions sur causes"],deliverables:["A3 ou 8D rempli","Plan d’actions","Leçon apprise"],pitfalls:["Faire un Ishikawa sans vérifier","Clore à la mise en œuvre au lieu du résultat"],special:"methods"},
  {id:"vsm",no:"07.01",title:"VSM et flux",category:"Flux",objective:"Comprendre pourquoi le temps de traversée vient souvent davantage des attentes et encours que du temps machine.",use:"Retards, WIP élevé, flux complexe ou lancement d’une transformation de flux.",steps:["Choisir une famille produit","Relever le flux réel","Mesurer CT, disponibilité, stocks et informations","Calculer lead time et VA/NVA","Identifier contrainte et boucles","Dessiner un futur testable"],checklist:["Client et demande","Takt","Temps de cycle","Changements de série","Disponibilité","Encours","Délais information","Fréquence transfert"],kpis:["Lead time","VA/NVA","WIP","Débit","OTIF"],deliverables:["Current State","Future State","Plan 30/60/90 jours"],pitfalls:["Dessiner depuis une salle","Cartographier toute l’usine d’un coup"]},
  {id:"bottleneck",no:"07.02",title:"Identifier et exploiter un goulot",category:"Flux",objective:"Trouver la contrainte réelle et protéger le débit du système.",use:"Files persistantes, saturation ou capacité perçue insuffisante.",steps:["Observer où la file est stable","Mesurer débit et saturation","Vérifier variabilité et mix","Exploiter la contrainte sans investissement","Subordonner l’amont et l’aval","Élever puis recommencer"],checklist:["File avant poste","Famine après poste","Temps perdu au goulot","Capacité démontrée","Aléas","Règles de priorité"],kpis:["Débit système","Temps utile goulot","WIP avant goulot","Lead time"],deliverables:["Fiche contrainte","Buffer visuel","Plan d’exploitation"],pitfalls:["Optimiser chaque machine","Déplacer le goulot sans suivi"]},
  {id:"five-s",no:"08.01",title:"5S utile et maintenu",category:"Stabilité",objective:"Réduire risques, recherches et anomalies au poste sans bureaucratie.",use:"Désorganisation visible ou standard impossible à tenir.",steps:["Débarrasser avec l’équipe","Ranger selon fréquence d’usage","Nettoyer pour inspecter","Standardiser visuellement","Faire tenir par le management quotidien"],checklist:["Zone rouge temporaire","Place nommée","Quantité définie","Accès ergonomique","Standard photo","Anomalie visible","Propriétaire"],kpis:["Temps de recherche","Anomalies détectées","Écart au standard","Actions closes"],deliverables:["Audit court","Standard photo","Plan d’action"],pitfalls:["Noter la propreté uniquement","Sanctionner les opérateurs pour un défaut de système"]},
  {id:"standard-work",no:"08.02",title:"Standard Work",category:"Stabilité",objective:"Décrire la meilleure manière connue aujourd’hui, observable et améliorable.",use:"Variabilité, défauts, formation ou transfert de pratique.",steps:["Observer plusieurs cycles","Distinguer séquence, temps et points clés","Impliquer l’opérateur","Tester le standard","Former et vérifier","Améliorer avec date de version"],checklist:["But","Périmètre","Séquence","Temps attendu","Point sécurité/qualité","Réaction à l’écart","Version et auteur"],kpis:["Adhérence","Temps de formation","Dispersion CT","FPY"],deliverables:["Standard opératoire","Standard management","Standard réunion/audit/maintenance"],pitfalls:["Écrire une procédure illisible","Figer une mauvaise pratique"]},
  {id:"smed",no:"09.01",title:"Kit chantier SMED",category:"Méthodes",objective:"Réduire du dernier produit bon au premier produit bon stable.",use:"Changement série long, variable ou créant des défauts de redémarrage.",steps:["Filmer et chronométrer","Séparer interne et externe","Convertir interne vers externe","Simplifier et paralléliser","Sécuriser réglages et outillages","Tester puis standardiser"],checklist:["Début/fin définis","Chaque tâche chronométrée","Déplacements tracés","Préparation externe","Réglages repérés","Premier produit bon inclus"],kpis:["Durée médiane","Dispersion","Temps interne","FPY démarrage","Gain capacité"],deliverables:["Fiche chrono","Spaghetti","Standard final","Mesure gain"],pitfalls:["Exclure les essais qualité","Acheter avant de simplifier"]},
  {id:"tpm",no:"10.01",title:"TPM et maintenance",category:"Maintenance",objective:"Réduire les pertes équipements selon criticité et causes dominantes.",use:"Pannes, micro-arrêts, maintenance réactive ou obsolescence.",steps:["Classer la criticité","Faire le Pareto des pertes","Mesurer MTBF/MTTR","Traiter les causes chroniques","Définir préventif/autonome/conditionnel","Sécuriser pièces et obsolescence"],checklist:["Sécurité","Impact client","Capacité secours","Fréquence panne","Durée réparation","Pièces critiques","Compétence rare","Qualité GMAO"],kpis:["MTBF","MTTR","Disponibilité","Préventif réalisé","Pannes répétitives"],deliverables:["Matrice criticité","Pareto pannes","Plan maintenance","Liste pièces critiques"],pitfalls:["Mesurer seulement le nombre de pannes","Confier la TPM uniquement à la maintenance"]},
  {id:"quality",no:"11.01",title:"Qualité et amélioration continue",category:"Qualité",objective:"Sécuriser le client, éliminer les causes et clarifier les rôles Qualité/Amélioration Continue.",use:"Défauts, réclamations, dérive process ou coût de non-qualité.",steps:["Contenir et tracer","Pareto défauts","Chercher le lieu de création","Prouver la cause","Mettre un poka-yoke ou contrôle adapté","Vérifier capabilité et tenue"],checklist:["FPY","PPM","Scrap","Rework","Coût non-qualité","Plan de contrôle","Réaction","QRQC"],kpis:["FPY","PPM","Coût non-qualité","Récurrence"],deliverables:["8D","Plan de contrôle","Standard de réaction"],pitfalls:["Ajouter du contrôle sans traiter la cause","Laisser l’AC porter seule la conformité produit"]},
  {id:"industrialization",no:"12.01",title:"Industrialisation robuste",category:"Industrialisation",objective:"Mettre en production un produit/process capable, ergonomique, maintenable et standardisé.",use:"Nouveau produit, nouveau process, transfert ou montée en cadence.",steps:["Cadrer demande et critères d’acceptation","Concevoir flux et capacité","Conduire AMDEC process","Valider outillage, ergonomie et contrôle","Former et démarrer par paliers","Mesurer capabilité et ramp-up"],checklist:["Takt et mix","CT par poste","Layout","Ergonomie","AMDEC","Plan contrôle","Maintenance","Compétences","Run at rate","REX"],kpis:["Capacité démontrée","Cpk/Ppk","FPY","Ramp-up","Écart budget/délai"],deliverables:["Dossier industrialisation","Plan de montée en cadence","Standard de transfert"],pitfalls:["Valider uniquement la cadence instantanée","Reporter maintenance et ergonomie après démarrage"]},
  {id:"multisite",no:"13.01",title:"Pilotage multisite et transférabilité",category:"Multisite",objective:"Déployer ce qui fonctionne sans imposer artificiellement la même solution partout.",use:"Bonne pratique prouvée ou écart de performance entre sites.",steps:["Prouver le résultat local","Écrire le standard local","Évaluer transférabilité","Piloter sur un deuxième site","Ajuster au contexte","Décider standard Groupe, déploiement ou non-transposable"],checklist:["Impact","Facilité","Compatibilité process","Investissement","Culture","Ressources","Réglementation","ROI"],kpis:["Pratiques validées","Pilotes deuxième site","Délai de transfert","Gain reproduit"],deliverables:["Matrice transférabilité","Catalogue bonnes pratiques","Plan Yokoten"],pitfalls:["Créer un classement toxique","Copier sans conditions de réussite"],special:"multisite"},
  {id:"benchmark",no:"13.02",title:"Benchmark contextualisé des 7 sites",category:"Multisite",objective:"Comparer pour apprendre et non pour désigner un gagnant.",use:"Revue Groupe et choix de sites pilotes.",steps:["Aligner définitions","Documenter produit/volume/mix/technologie","Normaliser si pertinent","Comparer pertes et tendances","Identifier une pratique explicative","Organiser visite croisée"],checklist:["Produits","Volumes","Technologies","Complexité","Mix","Organisation","Règle KPI","Période"],kpis:["Écarts explicables","Visites croisées","Pratiques testées"],deliverables:["Fiche A à G","Narratif de contexte","Hypothèses à tester"],pitfalls:["Comparer des moyennes brutes","Utiliser le benchmark pour sanctionner"]},
  {id:"governance",no:"13.03",title:"Gouvernance Excellence Opérationnelle Groupe",category:"Multisite",objective:"Arbitrer, soutenir et diffuser avec un comité utile.",use:"Mensuel, 60 à 90 minutes, avec décisions préparées.",steps:["Revoir sécurité et service","Examiner écarts Groupe","Arbitrer ressources et blocages","Revoir pilotes et bénéfices","Décider déploiements","Confirmer messages aux sites"],checklist:["DG/sponsor","Directions sites","Production","Qualité","Maintenance","Supply","Industrialisation","Décisions attendues"],kpis:["Décisions en séance","Blocages levés","Bénéfices validés","Actions Groupe en retard"],deliverables:["Charte comité","Ordre du jour","Journal des décisions"],pitfalls:["Faire remonter tous les détails","Transformer le comité en reporting"]},
  {id:"transverse",no:"14.01",title:"Faire avancer 7 sites sans lien hiérarchique",category:"Leadership",objective:"Construire influence et crédibilité par les faits, le service rendu et la co-construction.",use:"Management transversal quotidien.",steps:["Écouter les priorités du site","Aller au terrain","Apporter une méthode et non un jugement","Obtenir un sponsor explicite","Créer un réseau de relais","Rendre les résultats et auteurs visibles"],checklist:["Intérêt du site explicite","Relais local","Décision sponsor","Temps disponible","Bénéfice partagé","Reconnaissance équipe"],kpis:["Sites engagés","Relais actifs","Demandes spontanées","Standards adoptés"],deliverables:["Carte parties prenantes","Réseau relais Lean","Plan de communication"],pitfalls:["Utiliser le DG comme menace","S’attribuer les résultats locaux"]},
  {id:"change",no:"14.02",title:"Conduite du changement terrain",category:"Leadership",objective:"Transformer une amélioration en nouvelle façon de travailler qui tient.",use:"Dès la conception du changement, pas à la fin.",steps:["Nommer l’irritant partagé","Co-concevoir avec les utilisateurs","Tester petit","Mesurer bénéfice et contraintes","Former au poste","Faire tenir par le management"],checklist:["Pourquoi concret","Ce qui change/ne change pas","Utilisateur pilote","Retour court","Standard simple","Rituel de tenue"],kpis:["Adoption","Écarts au standard","Irritants supprimés","Suggestions terrain"],deliverables:["Plan parties prenantes","Pilote","Plan d’ancrage"],pitfalls:["Former sans impliquer","Confondre résistance et information utile"]},
  {id:"ai",no:"15.01",title:"IA et excellence opérationnelle",category:"Digital",objective:"Utiliser l’IA pour analyser et capitaliser, en laissant la décision aux responsables terrain.",use:"Synthèse Gemba, Pareto, historiques pannes, standards et préparation de réunions.",steps:["Définir la décision à aider","Retirer données sensibles inutiles","Vérifier qualité et contexte","Demander une analyse traçable","Contrôler au terrain","Faire valider la décision humaine"],checklist:["Source connue","Données minimales","Résultat vérifiable","Biais recherché","Responsable de décision","Trace de validation"],kpis:["Temps d’analyse gagné","Erreurs détectées","Décisions vérifiées","Réutilisation des leçons"],deliverables:["Prompt métier","Synthèse sourcée","Décision et validation"],pitfalls:["Présenter une suggestion IA comme un fait","Automatiser un processus instable"]},
  {id:"roadmap",no:"16.01",title:"Roadmap Lean 3 ans",category:"Stratégie",objective:"Stabiliser et mesurer, standardiser et déployer, puis autonomiser le système.",use:"Cadrage CODIR et revue semestrielle.",steps:["Année 1 : stabiliser et mesurer","Année 2 : standardiser et déployer","Année 3 : autonomiser et améliorer le système"],checklist:["Baseline","Jalons trimestriels","Pilotes","Compétences","Gouvernance","Bénéfices","Risques","Critère de passage"],kpis:["Maturité","Résultats SQCDP","Standards déployés","Autonomie résolution"],deliverables:["Vue graphique","Support CODIR","Jalons et risques"],pitfalls:["Planifier des outils","Lier l’ambition à un score sans résultat industriel"],special:"roadmap"},
  {id:"models",no:"17.01",title:"Bibliothèque de modèles terrain",category:"Modèles",objective:"Mettre le bon formulaire au moment exact où il aide à décider.",use:"Avant un audit, chantier, diagnostic, standard ou business case.",steps:["Choisir le problème","Prendre le modèle minimal","Remplir au terrain","Joindre preuve et mesure","Transformer en action","Archiver la leçon"],checklist:["Audit 360/5S/maintenance/management","Gemba","A3/8D/DMAIC/PDCA","VSM/SMED/TPM","SQCDP/Obeya/KPI","Plan actions/quick wins","Roadmap/benchmark","Standard/REX/ROI"],kpis:["Modèles réellement utilisés","Temps de remplissage","Actions générées"],deliverables:["24 modèles numériques/éditables"],pitfalls:["Créer un formulaire sans usage","Demander deux fois la même donnée"],special:"models"},
  {id:"cases",no:"18.01",title:"15 cas industriels guidés",category:"Entraînement",objective:"S’entraîner à partir du problème, des faits et de la mesure avant l’outil.",use:"Préparation de poste, coaching ou animation d’un atelier.",steps:["Lire le problème","Choisir première observation","Lister les données nécessaires","Proposer l’analyse","Choisir l’outil","Définir KPI et standardisation"],checklist:["Faits","Données","Cause","Action","Résultat","Transférabilité"],kpis:["Cas traités","Décisions argumentées","Erreurs de méthode détectées"],deliverables:["15 fiches complètes"],pitfalls:["Mémoriser une solution","Négliger le contexte multisite"],special:"cases"},
  {id:"questions",no:"18.02",title:"20 questions par interlocuteur",category:"Entretiens",objective:"Obtenir rapidement les faits, priorités, irritants et attentes de chaque rôle.",use:"Entretiens DG, direction site, production, maintenance, qualité, supply, chef d’équipe et opérateur.",steps:["Préparer 5 questions prioritaires","Écouter les exemples récents","Demander la preuve","Reformuler l’impact","Recouper au terrain","Restituer sans attribuer les critiques"],checklist:["Question ouverte","Exemple concret","Depuis quand","Mesure","Responsable","Décision bloquée"],kpis:["Entretiens réalisés","Hypothèses confirmées/infirmées","Irritants recoupés"],deliverables:["8 listes de 20 questions"],pitfalls:["Faire un interrogatoire","Promettre une action avant recoupement"],special:"questions"},
  {id:"direction",no:"19.01",title:"Support Direction — démarche multisite",category:"Direction",objective:"Présenter en 10 à 12 vues une démarche claire : diagnostic, pilote, mesure, standard et déploiement.",use:"DG, CODIR ou lancement de démarche.",steps:["Vision","Problèmes terrain","Diagnostic","Priorisation","Chantier pilote","Mesure","Standardisation","Déploiement","Gouvernance","Roadmap"],checklist:["Un message par vue","Décision attendue","Chiffres définis","Risques explicites","Prochaine étape"],kpis:["Décisions obtenues","Sponsors nommés","Ressources arbitrées"],deliverables:["Trame 10 vues","Synthèse 1 page"],pitfalls:["Présenter un catalogue Lean","Masquer les points à confirmer"]},
  {id:"bia-evidence",no:"20.01",title:"Registre faits, hypothèses et terrain",category:"Référentiel",objective:"Empêcher qu’une hypothèse sur BIA devienne un fait dans l’application.",use:"Pour toute donnée de contexte, benchmark, présentation ou paramétrage.",steps:["Classer l’information","Joindre la source si publique","Noter la date de consultation","Décrire l’hypothèse sans l’affirmer","Nommer le terrain ou la personne qui confirmera","Réviser le statut"],checklist:["A. Fait vérifié","B. Hypothèse probable","C. Point à confirmer","Source","Date","Propriétaire de validation"],kpis:["Faits sourcés","Hypothèses ouvertes","Points confirmés terrain"],deliverables:["Registre de preuve","Liste courte des adaptations restantes"],pitfalls:["Inventer une URL","Utiliser les données de démonstration comme données réelles"],special:"evidence"}
];

const DIAGNOSTIC_DOMAINS = ["Sécurité","Qualité","Coûts","Délais","Productivité","TRS / OEE","Maintenance","Organisation","Management","Flux","Stocks","Encours","Logistique interne","Planification","Approvisionnement","Standards","5S","Compétences","Résolution de problèmes","Industrialisation","Automatisation","Digitalisation","Énergie","RSE","Ergonomie","Culture Lean"];

const KPI_DICTIONARY = [
  ["TRS / OEE","Disponibilité × Performance × Qualité","%","Comprendre les pertes d’un équipement requis","Quotidien / hebdo","Production","Temps requis et codes d’arrêt non alignés"],
  ["Disponibilité","Temps de fonctionnement / Temps requis","%","Voir la perte liée aux arrêts","Équipe / jour","Production + Maintenance","Exclure trop facilement des arrêts"],
  ["Performance","Production réelle / Production théorique au temps de fonctionnement","%","Voir vitesse et micro-arrêts","Équipe / jour","Production","Cadence idéale irréaliste"],
  ["Qualité TRS","Pièces bonnes / Pièces totales","%","Voir la perte de rendement qualité","Équipe / jour","Qualité + Production","Oublier rebuts de démarrage"],
  ["OTD","Livraisons à l’heure / Livraisons totales","%","Fiabilité de la date promise","Hebdo / mensuel","Supply","Redéfinir la date promise après retard"],
  ["OTIF","Livraisons à l’heure et complètes / Livraisons totales","%","Service réellement rendu","Hebdo / mensuel","Supply","Mélanger commandes et lignes"],
  ["Lead Time","Date fin − date début du périmètre","Temps","Voir le temps total vécu par le produit/client","Hebdo","Process owner","Périmètre variable"],
  ["Temps de cycle","Temps entre deux sorties consécutives","s, min","Comparer rythme réel et takt","Équipe","Production","Confondre temps opératoire et cycle ligne"],
  ["Takt Time","Temps net disponible / Demande client","s/pièce","Donner le rythme nécessaire","À chaque variation demande","Planification","Utiliser une moyenne annuelle"],
  ["WIP","Unités commencées non terminées","unités / € / jours","Rendre visible l’encours","Quotidien","Production + Supply","Ne pas compter les zones cachées"],
  ["FPY","Bon du premier coup / Total traité","%","Mesurer la qualité au premier passage","Équipe / jour","Qualité","Réintégrer les retouches comme bonnes"],
  ["PPM","Défauts / Unités × 1 000 000","ppm","Comparer de faibles taux de défaut","Mensuel","Qualité","Dénominateur incohérent"],
  ["Scrap","Quantité ou coût rebut / Production totale","% ou €","Mesurer la destruction de valeur","Jour / mois","Qualité + Finance","Valorisation partielle"],
  ["Rework","Temps ou quantité retouchée / Total","% / h","Voir le travail caché","Jour / semaine","Production","Retouches non déclarées"],
  ["MTBF","Temps de fonctionnement / Nombre de pannes","h","Mesurer la fiabilité","Hebdo / mensuel","Maintenance","Changer la définition de panne"],
  ["MTTR","Temps total de réparation / Nombre de pannes","min / h","Mesurer la maintenabilité","Hebdo / mensuel","Maintenance","Inclure attente pièce sans la distinguer"],
  ["Adhérence planning","Ordres réalisés comme planifiés / Ordres planifiés","%","Voir stabilité et exécution du plan","Jour / semaine","Planification","Replanifier pour embellir"],
  ["Productivité","Sortie bonne / Ressource consommée","u/h, h/u","Relier production et ressources","Jour / semaine","Production","Comparer produits de complexité différente"],
  ["Coût de non-qualité","Rebuts + retouches + tris + retours + garanties","€ / % CA","Prioriser économiquement la qualité","Mensuel","Qualité + Finance","Oublier coûts cachés"],
  ["Taux de service","Demande satisfaite selon définition convenue","%","Voir disponibilité pour le client","Hebdo / mensuel","Supply","Définition différente de l’OTIF"],
  ["Rotation stock","Consommation annuelle / Stock moyen","tours/an","Voir capital immobilisé","Mensuel","Supply + Finance","Masquer les dormants dans la moyenne"]
];

const HUNDRED_DAY_PHASES = [
  {period:"J0–J30 · Comprendre",objective:"Créer la confiance et une base factuelle commune.",actions:"Rencontrer le sponsor, visiter les 7 sites, suivre les flux, vérifier les définitions KPI, cartographier projets et irritants.",people:"DG, responsable développement, directions sites, production, qualité, maintenance, supply, industrialisation, chefs d’équipe, opérateurs.",data:"Sécurité, qualité, service, TRS, productivité, stocks, coûts de non-qualité, pannes, organigrammes, projets, standards.",deliverable:"Carte du système, diagnostic initial, top problèmes par site, registre faits/hypothèses/terrain.",decision:"Périmètres à approfondir et risques à sécuriser.",risk:"Être perçu comme auditeur Groupe ou annoncer trop tôt des solutions.",kpi:"7 sites vus, 80 % des définitions KPI validées, risques immédiats attribués.",questions:"Qu’est-ce qui empêche aujourd’hui de tenir les engagements ? Où les équipes perdent-elles le plus de temps ?"},
  {period:"J31–J60 · Prioriser et expérimenter",objective:"Choisir peu de problèmes et produire une première preuve de résultat.",actions:"Prioriser impact/urgence/faisabilité, choisir un chantier pilote, fiabiliser baseline, tester contre-mesures, installer SQCDP minimal.",people:"Sponsor local, équipe pilote, contrôle de gestion, relais Lean, fonctions support nécessaires.",data:"Mesure avant, causes stratifiées, capacité, variabilité, coûts, contraintes ressources.",deliverable:"A3 pilote, business case, plan 30/60/90 jours, premiers standards de réaction.",decision:"Continuer, ajuster ou arrêter le pilote ; ressources à arbitrer.",risk:"Multiplier les quick wins sans traiter un problème structurant.",kpi:"1 pilote lancé, baseline validée, 2 à 4 quick wins mesurés, actions à l’heure > 80 %.",questions:"Quelle preuve ferait dire à l’équipe que le pilote fonctionne ? Qu’est-ce qui peut empêcher sa tenue ?"},
  {period:"J61–J100 · Consolider et déployer",objective:"Faire tenir le résultat et tester la transférabilité.",actions:"Confirmer gains, écrire standard local, former, auditer tenue, analyser transfert, piloter sur un deuxième site, installer gouvernance Groupe.",people:"DG/sponsor, directions sites, pilote deuxième site, réseau relais, RH/formation.",data:"Résultat avant/après, dispersion, adoption, ressources, compatibilité process, ROI.",deliverable:"Standard validé, matrice de transférabilité, catalogue bonnes pratiques, roadmap 3 ans, restitution J100.",decision:"Standard local, déployable, standard Groupe ou non-transposable.",risk:"Déployer avant stabilisation ou imposer un standard sans conditions de réussite.",kpi:"Gain tenu 4 semaines, second site engagé, comité Groupe actif, feuille de route arbitrée.",questions:"Le résultat tient-il sans l’équipe projet ? Quelles conditions doivent rester locales ?"}
];

const HUNDRED_DAY_WEEKS = [
  "S1 — Sponsor, mandat, attentes et règles de confidentialité", "S2 — Site 1 : observation, KPI, entretiens, risques", "S3 — Sites 2 et 3 : diagnostic court et comparaison des définitions", "S4 — Sites 4 et 5 : flux, maintenance, qualité, management", "S5 — Sites 6 et 7 : diagnostic et synthèse J30", "S6 — Normaliser les données et prioriser les problèmes", "S7 — Cadrer le chantier pilote et sa baseline", "S8 — Mesurer au terrain et tester les causes", "S9 — Première contre-mesure et quick wins", "S10 — Revue J60, arbitrage et ajustement", "S11 — Confirmer résultat et variabilité", "S12 — Écrire le standard local et former", "S13 — Évaluer la transférabilité", "S14 — Préparer ou lancer le pilote deuxième site", "S15 — Installer gouvernance, roadmap et restitution J100"
];

const GEMBA_QUESTIONS = ["Que devrait-il se passer ?","Que se passe-t-il réellement ?","Pourquoi ?","Comment le savons-nous ?","Quel est l’impact ?","Depuis quand ?","Qui est concerné ?","Quelle est la cause probable ?"];
const MUDAS = ["Défauts","Surproduction","Attentes","Compétences non utilisées","Transports","Stocks","Mouvements","Surprocess"];

const PROBLEM_METHODS = [
  ["A3","Problème transverse de complexité moyenne qui demande alignement et coaching","Urgence nécessitant d’abord une contention ou problème simple résolu au poste","Rebuts de démarrage : écart 6 %, cause confirmée sur réglage non repéré, contre-mesure visuelle, FPY vérifié 4 semaines"],
  ["PDCA","Amélioration incrémentale et test rapide d’une hypothèse","Crise client avec exigences formelles de traçabilité","Tester une nouvelle règle FIFO sur une zone pendant deux semaines puis ajuster"],
  ["DMAIC","Problème complexe, très mesurable et à forte variabilité","Cause déjà évidente ou solution obligatoire","Réduire la dispersion du temps de cycle d’une ligne multi-références"],
  ["8D","Défaut client ou problème exigeant contention, équipe et preuve de non-récurrence","Simple irritant sans risque ni besoin de traçabilité formelle","Réclamation pour pièce mal identifiée : tri, cause système, poka-yoke et validation client"],
  ["5 Pourquoi","Remonter rapidement une chaîne causale simple après observation","Système complexe à causes multiples ou débat sans données","Arrêt car capteur sale → accès difficile → nettoyage absent du standard → fréquence et responsable ajoutés"],
  ["Ishikawa","Explorer avec l’équipe des familles de causes avant vérification","Pour voter la cause la plus populaire","Défaut de collage : Matière, Méthode, Machine, Main-d’œuvre, Milieu, Mesure puis tests ciblés"],
  ["Pareto","Prioriser catégories de pertes à partir de données fiables","Tirer une conclusion causale","Trois codes représentent 72 % des heures d’arrêt : l’analyse commence par le premier"],
  ["QQOQCP","Décrire précisément un problème ou une action","Prouver une cause racine","Quoi, Qui, Où, Quand, Comment, Combien, Pourquoi pour cadrer les retards d’expédition"]
];

const SQCDP_LEVELS = [
  ["Atelier / ligne","Quotidien, 10 min","Chef d’équipe + équipe","Écarts du dernier poste, sécurité, qualité, débit, présence","Action immédiate ou escalade au site le jour même"],
  ["Site","Quotidien ou 3×/semaine, 20 min","Direction site + fonctions","Écarts non résolus, arbitrages ressources, risque client","Décision site ou escalade Groupe sous 48 h"],
  ["Groupe","Hebdomadaire synthèse / mensuel Obeya","DG/sponsor + directions sites","Tendances, risques majeurs, projets, déploiements","Arbitrage Groupe, sponsor, standard ou investissement"]
];

const TRANSFER_CRITERIA = [["Impact",20],["Facilité",10],["Compatibilité process",20],["Investissement",10],["Culture",10],["Ressources",10],["Réglementation",10],["ROI",10]];

const FIELD_MODELS = [
  ["Audit Lean / Diagnostic 360","Calcul et radar intégrés"],["Audit 5S","Checklist courte + standard photo"],["Audit maintenance","Criticité, Pareto, préventif, pièces"],["Audit management","Rituels, escalade, coaching"],["Gemba 60 min","Observation + création d’action"],["A3","Problème, cible, cause, contre-mesure, résultat"],["8D","Contention à prévention de récurrence"],["DMAIC","Define à Control"],["PDCA","Test court et apprentissage"],["VSM","Relevé Current/Future State"],["SMED","Chrono interne/externe"],["TPM","Criticité et pertes équipement"],["SQCDP","Atelier/site/Groupe"],["Obeya","11 zones de décision"],["KPI","Dictionnaire et propriétaire"],["Plan d’action","Qui/quoi/quand/preuve"],["Quick Wins","Impact/effort/risque"],["Roadmap","Jalons, KPI, risques"],["Matrice maturité","Score 0 à 5"],["Benchmark site","Contexte avant chiffres"],["Standard Work","Séquence/temps/points clés"],["Lessons Learned","Résultat, condition, limite"],["Catalogue bonnes pratiques","Preuve et transférabilité"],["Business case / ROI","Coût complet, gain prudent, délai retour"]
];

const CASES = [
  {t:"Changement outillage trop long",p:"52 min, très variable",o:"Filmer dernier bon → premier bon",d:"Temps par tâche, interne/externe, essais",a:"70 % du temps est interne et 18 min sont des recherches",tool:"SMED + 5S ciblé",action:"Préparer hors machine, chariot dédié, repères de réglage",kpi:"Médiane 52 → 28 min, FPY démarrage",standard:"Standard vidéo et checklist",deploy:"Déployable si outillages et sécurité comparables"},
  {t:"TRS faible",p:"TRS 61 %",o:"Observer les pertes par créneau",d:"Disponibilité, performance, qualité, codes arrêts",a:"Micro-arrêts non codés dominants",tool:"Pareto + TPM",action:"Revoir détection, standard réaction et nettoyage capteur",kpi:"TRS et minutes micro-arrêts",standard:"Code arrêt et réaction opérateur",deploy:"Standard de mesure Groupe, causes locales"},
  {t:"Panne chronique",p:"Convoyeur s’arrête chaque semaine",o:"Conditions avant panne et interventions",d:"MTBF, MTTR, composant, charge",a:"Désalignement après changement de format",tool:"5 Pourquoi + TPM",action:"Butée robuste et contrôle autonome",kpi:"MTBF ×3",standard:"Point de contrôle au changement",deploy:"Oui sur convoyeurs similaires"},
  {t:"Encours excessifs",p:"12 jours de WIP",o:"Compter et dater par étape",d:"Lead time, CT, demande, files",a:"Lancement par gros lots et goulot masqué",tool:"VSM + TOC",action:"Réduire lots, FIFO avant contrainte",kpi:"WIP 12 → 6 jours",standard:"Règle de lancement",deploy:"Pilote deuxième famille avant multisite"},
  {t:"Retards livraison",p:"OTIF 82 %",o:"Reconstituer trois commandes",d:"Chronologie, replanifications, ruptures",a:"Priorités changent quotidiennement",tool:"VSM information + adhérence planning",action:"Gel court et règle d’escalade",kpi:"OTIF, adhérence planning",standard:"Rituel supply quotidien",deploy:"Déployable avec paramètres locaux"},
  {t:"Défaut récurrent",p:"Rayure sur 4 % des pièces",o:"Chercher lieu de création",d:"Produit, poste, équipe, support",a:"Support de transfert usé",tool:"Pareto + 8D",action:"Containment, remplacement, poka-yoke d’usure",kpi:"FPY, récurrence 8 semaines",standard:"Contrôle support",deploy:"Catalogue si même support ailleurs"},
  {t:"Poste désorganisé",p:"6 min de recherche par ordre",o:"Tracer gestes et objets",d:"Fréquence usage, distance, anomalies",a:"Outillage partagé sans emplacement",tool:"5S + Standard Work",action:"Point d’usage et quantité définie",kpi:"Recherche < 1 min",standard:"Photo + audit 3 questions",deploy:"Principe Groupe, layout local"},
  {t:"Écart entre deux sites",p:"TRS 12 points d’écart",o:"Aligner produit, mix et calcul",d:"Temps requis, technologie, séries",a:"7 points viennent de définitions différentes",tool:"Benchmark contextualisé",action:"Aligner calcul puis visite croisée",kpi:"Écart comparable",standard:"Dictionnaire KPI Groupe",deploy:"Oui pour définition, non pour cible brute"},
  {t:"Bonne pratique à déployer",p:"Démarrage −18 % micro-arrêts",o:"Voir la pratique et conditions",d:"Avant/après, ressources, limites",a:"Gain tient 8 semaines",tool:"Matrice transférabilité",action:"Pilote sur un second site",kpi:"Gain reproduit",standard:"Standard local puis version Groupe",deploy:"Selon compatibilité process"},
  {t:"Standard Groupe rejeté",p:"Site ne l’applique pas",o:"Observer le travail et écouter les écarts",d:"Contraintes produit, sécurité, charge",a:"Une étape est incompatible avec le mix local",tool:"PDCA + conduite changement",action:"Conserver exigences communes, adapter moyen",kpi:"Adoption et résultat",standard:"Socle Groupe + annexe locale",deploy:"Oui avec règle d’adaptation"},
  {t:"Manque de données",p:"Arrêts estimés",o:"Échantillon manuel sur 3 équipes",d:"Temps, motif, source",a:"Codes actuels couvrent 45 % des pertes",tool:"Plan de mesure",action:"6 codes simples et contrôle quotidien",kpi:"Complétude > 90 %",standard:"Définition et propriétaire",deploy:"Standard Groupe possible"},
  {t:"Productivité différente entre lignes",p:"Écart 25 %",o:"Comparer mix, séquence et contraintes",d:"Heures directes, CT, FPY, attente",a:"Une ligne absorbe les retouches amont",tool:"Stratification + VSM",action:"Séparer charge normale et retouche",kpi:"Productivité normalisée",standard:"Règle de calcul",deploy:"Définition Groupe"},
  {t:"Approvisionnement instable",p:"9 ruptures/mois",o:"Suivre article de la demande à la ligne",d:"Délai, variation, stock exact, paramètre ERP",a:"Délai paramétré inférieur au réel",tool:"Pareto + PDCA supply",action:"Corriger paramètres et kanban pilote",kpi:"Ruptures, couverture",standard:"Revue paramètres",deploy:"Oui par classe article"},
  {t:"Nouvelle ligne",p:"Montée en cadence incertaine",o:"Run at rate représentatif",d:"CT, FPY, arrêts, ergonomie, capabilité",a:"Poste contrôle dépasse le takt",tool:"AMDEC + équilibrage",action:"Modifier séquence et automatiser mesure",kpi:"Capacité démontrée, FPY",standard:"Dossier acceptation",deploy:"REX vers prochains projets"},
  {t:"Opérateurs réticents",p:"Audit et standards non utilisés",o:"Écouter irritants et tester au poste",d:"Temps ajouté, anomalies résolues",a:"Support double-saisit une donnée sans retour",tool:"Co-construction + PDCA",action:"Supprimer doublon et restituer résultat",kpi:"Usage, irritants clos",standard:"Standard construit avec utilisateurs",deploy:"Principe de conception Groupe"}
];

const COMMON_QUESTIONS = [
  "Quel résultat devait être atteint cette semaine ?","Quel écart vous préoccupe le plus aujourd’hui ?","Pouvez-vous me montrer un exemple récent ?","Comment mesurez-vous cet écart ?","Depuis quand existe-t-il ?","Quel est son impact sécurité, client, délai ou coût ?","Quelle cause a été vérifiée et comment ?","Quelle action est en cours et qui la porte ?","Qu’est-ce qui bloque la décision ?","Quel standard devrait s’appliquer ?","Comment voyez-vous qu’il n’est pas tenu ?","Quelle donnée est la moins fiable ?"
];
const ROLE_QUESTIONS = {
  "DG Groupe":["Quels résultats industriels conditionnent la stratégie des trois prochaines années ?","Qu’attendez-vous concrètement de la fonction Groupe à J100 ?","Quels sujets nécessitent votre sponsoring explicite ?","Quelle autonomie souhaitez-vous laisser aux sites ?","Quels risques ne doivent jamais être masqués ?","Où une standardisation Groupe créerait le plus de valeur ?","Comment voulez-vous arbitrer les investissements multisites ?","À quoi reconnaîtrez-vous que le système devient autonome ?"],
  "Directeur de site":["Quelles sont vos trois priorités industrielles du trimestre ?","Où perdez-vous le plus de service ou de marge ?","Quel chantier passé a réellement tenu ?","Quel standard Groupe vous aide et lequel vous contraint ?","Quelles décisions attendez-vous du Groupe ?","Quel secteur dois-je voir en premier ?","Qui sont vos relais naturels ?","Quel risque local est mal compris hors du site ?"],
  "Responsable production":["Quel écart revient à chaque réunion ?","Où se forme la file la plus stable ?","Quel temps de cycle est le plus variable ?","Quand le planning change-t-il et pourquoi ?","Quelles pertes TRS sont réellement codées ?","Quel standard est le plus difficile à tenir ?","Où les opérateurs compensent-ils le système ?","Quel essai pouvons-nous mener cette semaine ?"],
  "Responsable maintenance":["Quels équipements sont réellement critiques ?","Quel Pareto utilisez-vous : nombre ou heures perdues ?","Quelles pannes se répètent après réparation ?","Quels MTBF et MTTR sont fiables ?","Quel préventif est reporté et pourquoi ?","Quelles pièces créent le plus d’attente ?","Quelle maintenance autonome est réaliste ?","Quelle obsolescence peut arrêter le site ?"],
  "Responsable qualité":["Quel défaut coûte le plus et lequel revient le plus ?","Où les défauts sont-ils créés et détectés ?","Quel FPY reflète vraiment le process ?","Quelles retouches restent invisibles ?","Quel plan de contrôle ajoute peu de valeur ?","Quels 8D ne sont pas durablement clos ?","Quel poka-yoke a le mieux fonctionné ?","Où s’arrête le rôle Qualité et commence l’amélioration système ?"],
  "Responsable supply":["Quelles commandes deviennent urgentes et pourquoi ?","Quelle définition OTD/OTIF utilisez-vous ?","Où la planification devient-elle instable ?","Quels articles causent les ruptures ?","Quels stocks sont protecteurs, dormants ou masquants ?","Quel paramètre ERP est le moins fiable ?","Quelle règle de priorité est réellement appliquée ?","Quel fournisseur nécessite une action structurée ?"],
  "Chef d’équipe":["Quel est le premier écart que vous regardez au démarrage ?","Que pouvez-vous résoudre sans aide ?","Qu’escaladez-vous et sous quel délai ?","Quelle réunion vous aide vraiment ?","Quel standard est ambigu ?","Où votre équipe perd-elle du temps ?","Quelle compétence manque sur certains créneaux ?","Quelle amélioration récente a facilité le travail ?"],
  "Opérateur":["Que devrait-il se passer à ce poste ?","Qu’est-ce qui vous empêche de faire du bon travail du premier coup ?","Que cherchez-vous ou attendez-vous souvent ?","Quel défaut voyez-vous avant les autres ?","Que faites-vous quand la machine s’arrête ?","Quelle consigne est difficile à appliquer ?","Quel risque ou geste pénible doit être traité ?","Si vous pouviez supprimer un irritant demain, lequel ?"]
};

const ROADMAP_YEARS = [
  ["Année 1 · Stabiliser et mesurer","Définitions KPI, management quotidien, diagnostics, résolution de problèmes, pilotes ciblés","Baseline fiable, écarts visibles, premiers gains tenus","Données faibles, surcharge de chantiers"],
  ["Année 2 · Standardiser et déployer","Standards locaux prouvés, matrice de transférabilité, pilotes deuxième site, réseau relais","Gains reproduits, pratiques partagées, rituels alignés","Copie sans contexte, fatigue du changement"],
  ["Année 3 · Autonomiser et améliorer le système","Coaching managers, compétences problèmes, audits de système, portefeuille bénéfices","Sites autonomes, Groupe arbitre et accélère","Dépendance à une personne, maturité décorative"]
];

let toolkitState = {module:null,problem:null,category:"Tous",questionRole:"DG Groupe"};

function toolkitJson(key,fallback){try{return JSON.parse(localStorage.getItem(key))||fallback}catch(_e){return fallback}}
function toolkitSave(key,value){localStorage.setItem(key,JSON.stringify(value))}
function toolkitModule(id){return TOOL_MODULES.find(x=>x.id===id)}
function toolkitProblem(id){return TOOL_PROBLEMS.find(x=>x.id===id)}

function renderToolkit(){
  const root=$("toolsView");
  if(!root)return;
  if(!(data.toolkitRuns||[]).length)data.toolkitRuns=toolkitJson("biaV4ToolkitRuns",[]);
  if(toolkitState.module){root.innerHTML=renderToolDetail(toolkitModule(toolkitState.module));return}
  if(toolkitState.problem){root.innerHTML=renderProblemDetail(toolkitProblem(toolkitState.problem));return}
  const categories=["Tous",...new Set(TOOL_MODULES.map(x=>x.category))];
  const visible=toolkitState.category==="Tous"?TOOL_MODULES:TOOL_MODULES.filter(x=>x.category===toolkitState.category);
  const activeRuns=(data.toolkitRuns||[]).filter(x=>x.site_id===siteId&&x.status!=="termine");
  root.innerHTML=`
    <div class="toolkit-hero"><p class="eyebrow">Bibliothèque professionnelle intégrée</p><h1>Partir du problème. Agir au terrain.</h1><p class="hint">Des parcours courts, des checklists et des modèles utilisables demain matin — sans choisir un outil avant d’avoir observé et mesuré.</p><div class="toolkit-search"><input id="toolSearch" type="search" placeholder="Ex. stocks, pannes, TRS, 100 jours…" aria-label="Rechercher un outil"><button class="btn" id="clearToolSearch">Effacer</button></div></div>
    <div class="fact-note section"><b>Données BIA :</b> les valeurs affichées dans le mode démo sont des exemples, pas des faits réels. Toute information de contexte doit être classée Fait vérifié, Hypothèse probable ou Point à confirmer sur le terrain.</div>
    ${activeRuns.length?`<div class="section"><div class="section-title"><h2>Parcours en cours</h2><span class="badge">${activeRuns.length}</span></div><div class="list">${activeRuns.slice(0,3).map(x=>`<button class="problem-card" data-open-tool="${x.module_id}"><div><b>${esc(x.title)}</b><small>${esc(SITES.find(s=>s.id===x.site_id)?.name||x.site_id)} · ${esc(x.status)}</small></div><span>→</span></button>`).join("")}</div></div>`:""}
    <div class="section"><div class="section-title"><div><h2>J’ai un problème</h2><p class="hint">Le premier écran vous oriente vers l’observation, la mesure et l’outil minimal.</p></div><span class="badge">${TOOL_PROBLEMS.length} routes</span></div><div class="problem-grid">${TOOL_PROBLEMS.map(x=>`<button class="problem-card toolkit-searchable" data-problem-route="${x.id}" data-search-text="${esc((x.problem+" "+x.signal+" "+x.tools.join(" ")).toLowerCase())}"><div><b>${esc(x.problem)}</b><small>${esc(x.signal)}</small></div><span>→</span></button>`).join("")}</div></div>
    <div class="section"><div class="section-title"><div><h2>Bibliothèque opérationnelle</h2><p class="hint">Un outil = un usage, une séquence terrain et une décision attendue.</p></div><span class="badge">${TOOL_MODULES.length} modules</span></div><div class="tool-chips">${categories.map(c=>`<button class="chip ${c===toolkitState.category?"active":""}" data-tool-category="${esc(c)}">${esc(c)}</button>`).join("")}</div><div class="toolkit-grid">${visible.map(x=>`<button class="tool-card toolkit-searchable" data-open-tool="${x.id}" data-search-text="${esc((x.title+" "+x.category+" "+x.objective+" "+x.checklist.join(" ")).toLowerCase())}"><span class="tool-no">${esc(x.no)} · ${esc(x.category)}</span><h3>${esc(x.title)}</h3><p>${esc(x.objective)}</p><span class="arrow">→</span></button>`).join("")}</div><div id="toolNoResult" class="empty section" hidden>Aucun outil trouvé. Essayez un symptôme plus simple.</div></div>`;
}

function renderProblemDetail(route){
  if(!route)return `<div class="empty">Route introuvable.</div>`;
  return `<div class="tool-detail"><button class="btn secondary" data-back-tools>← Tous les outils</button><div class="tool-head section"><span class="tool-no">ARBRE DE DÉCISION</span><h1>${esc(route.problem)}</h1><p class="intro">${esc(route.signal)}</p><div class="tag-list">${route.tools.map(x=>`<span class="tag">${esc(x)}</span>`).join("")}</div></div><div class="tool-block"><h2>Chemin recommandé</h2><div class="route-flow"><div><b>Problème</b><br>${esc(route.problem)}</div><div><b>Observation terrain</b><br>${esc(route.observe)}</div><div><b>Mesure</b><br>${esc(route.measure)}</div><div><b>Outil(s) après les faits</b><br>${esc(route.tools.join(" → "))}</div><div><b>Première action demain matin</b><br>${esc(route.first)}</div></div><div class="tool-actions"><button class="btn" data-problem-action="${route.id}">Créer cette première action</button><button class="btn secondary" data-print-tool>Imprimer / PDF</button></div></div></div>`;
}

function renderToolDetail(module){
  if(!module)return `<div class="empty">Module introuvable.</div>`;
  const progress=toolkitJson("biaV4ToolProgress",{}), done=progress[module.id]||[], pct=Math.round(done.length/Math.max(module.checklist.length,1)*100);
  return `<div class="tool-detail"><button class="btn secondary" data-back-tools>← Bibliothèque</button><div class="tool-head section"><span class="tool-no">${esc(module.no)} · ${esc(module.category)}</span><h1>${esc(module.title)}</h1><p class="intro">${esc(module.objective)}</p><div class="fact-note"><b>Quand l’utiliser :</b> ${esc(module.use)}</div><div class="tool-actions"><button class="btn" data-start-tool="${module.id}">Démarrer sur ${esc(current().name)}</button><button class="btn secondary" data-tool-action="${module.id}">Créer une action</button><button class="btn secondary" data-print-tool>Imprimer / PDF</button></div></div><div class="tool-detail-grid"><div class="tool-block"><h2>Séquence terrain</h2>${module.steps.map((x,i)=>`<div class="tool-step"><span>${i+1}</span><div>${esc(x)}</div></div>`).join("")}</div><div class="tool-block"><div class="section-title"><h2>Checklist de lancement</h2><span class="badge" id="toolProgressText">${pct} %</span></div><div class="tool-progress"><span id="toolProgressBar" style="width:${pct}%"></span></div>${module.checklist.map((x,i)=>`<label class="tool-check"><input type="checkbox" data-tool-check="${i}" data-module="${module.id}" ${done.includes(i)?"checked":""}><span>${esc(x)}</span></label>`).join("")}</div><div class="tool-block"><h2>KPI utiles</h2><ul>${module.kpis.map(x=>`<li>${esc(x)}</li>`).join("")}</ul></div><div class="tool-block"><h2>Livrables attendus</h2><ul>${module.deliverables.map(x=>`<li>${esc(x)}</li>`).join("")}</ul></div></div><div class="tool-block"><h2>Pièges à éviter</h2><div class="tag-list">${module.pitfalls.map(x=>`<span class="tag">${esc(x)}</span>`).join("")}</div></div>${renderToolSpecial(module)}</div>`;
}

function renderToolSpecial(module){
  switch(module.special){
    case "hundred": return `<div class="tool-block"><h2>Plan détaillé par phase</h2><div class="timeline">${HUNDRED_DAY_PHASES.map(x=>`<article class="timeline-card"><h3>${esc(x.period)}</h3><p><b>Objectif :</b> ${esc(x.objective)}</p><p><b>Actions :</b> ${esc(x.actions)}</p><p><b>Personnes :</b> ${esc(x.people)}</p><p><b>Données :</b> ${esc(x.data)}</p><p><b>Livrable :</b> ${esc(x.deliverable)}</p><p><b>Décision :</b> ${esc(x.decision)}</p><p><b>Risque :</b> ${esc(x.risk)}</p><p><b>KPI :</b> ${esc(x.kpi)}</p><p><b>Questions :</b> ${esc(x.questions)}</p></article>`).join("")}</div></div><div class="tool-block"><h2>Calendrier semaine par semaine</h2><ol>${HUNDRED_DAY_WEEKS.map(x=>`<li>${esc(x)}</li>`).join("")}</ol></div>`;
    case "diagnostic": return renderDiagnosticSpecial();
    case "gemba": return `<div class="tool-block"><h2>Les 8 MUDAS à rechercher</h2><div class="tag-list">${MUDAS.map(x=>`<span class="tag">${esc(x)}</span>`).join("")}</div></div><div class="tool-block"><h2>Questions de preuve</h2><ol>${GEMBA_QUESTIONS.map(x=>`<li>${esc(x)}</li>`).join("")}</ol></div>`;
    case "kpi": return renderKpiSpecial();
    case "methods": return `<div class="tool-block"><h2>Choisir la méthode proportionnée</h2>${PROBLEM_METHODS.map(x=>`<details class="accordion"><summary>${esc(x[0])}</summary><div><p><b>Quand :</b> ${esc(x[1])}</p><p><b>Quand ne pas l’utiliser :</b> ${esc(x[2])}</p><p><b>Exemple rempli :</b> ${esc(x[3])}</p></div></details>`).join("")}</div>`;
    case "sqcdp": return `<div class="tool-block data-table"><h2>Architecture et escalade</h2><table><thead><tr><th>Niveau</th><th>Rythme</th><th>Participants</th><th>Contenu</th><th>Sortie attendue</th></tr></thead><tbody>${SQCDP_LEVELS.map(x=>`<tr>${x.map(v=>`<td>${esc(v)}</td>`).join("")}</tr>`).join("")}</tbody></table></div>`;
    case "multisite": return `<div class="tool-block"><h2>Matrice de transférabilité</h2>${TRANSFER_CRITERIA.map(x=>`<div class="metric-row"><span>${esc(x[0])}</span><div class="scorebar"><span style="width:${x[1]*5}%"></span></div><b>${x[1]} %</b></div>`).join("")}<p class="hint">Score indicatif à compléter par des preuves. Une contrainte sécurité ou réglementaire reste éliminatoire.</p></div><div class="tool-block"><h2>Processus Groupe</h2><div class="route-flow">${["Problème","Expérimentation locale","Résultat démontré","Standard local","Analyse transférabilité","Pilote deuxième site","Ajustement","Standard Groupe éventuel"].map(x=>`<div>${esc(x)}</div>`).join("")}</div></div>`;
    case "roadmap": return `<div class="tool-block"><h2>Vue 3 ans</h2><div class="timeline">${ROADMAP_YEARS.map(x=>`<article class="timeline-card"><h3>${esc(x[0])}</h3><p><b>Priorités :</b> ${esc(x[1])}</p><p><b>Jalons :</b> ${esc(x[2])}</p><p><b>Risques :</b> ${esc(x[3])}</p></article>`).join("")}</div></div>`;
    case "models": return `<div class="tool-block data-table"><h2>24 modèles disponibles</h2><table><thead><tr><th>Modèle</th><th>Usage intégré</th></tr></thead><tbody>${FIELD_MODELS.map(x=>`<tr><td><b>${esc(x[0])}</b></td><td>${esc(x[1])}</td></tr>`).join("")}</tbody></table></div>`;
    case "cases": return `<div class="tool-block"><h2>Cas pratiques</h2>${CASES.map((x,i)=>`<details class="accordion"><summary>${i+1}. ${esc(x.t)}</summary><div><p><b>Problème :</b> ${esc(x.p)}</p><p><b>Première observation :</b> ${esc(x.o)}</p><p><b>Données :</b> ${esc(x.d)}</p><p><b>Analyse :</b> ${esc(x.a)}</p><p><b>Outil :</b> ${esc(x.tool)}</p><p><b>Action :</b> ${esc(x.action)}</p><p><b>KPI :</b> ${esc(x.kpi)}</p><p><b>Standardisation :</b> ${esc(x.standard)}</p><p><b>Multisite :</b> ${esc(x.deploy)}</p></div></details>`).join("")}</div>`;
    case "questions": return renderQuestionsSpecial();
    case "evidence": return renderEvidenceSpecial();
    default: return "";
  }
}

function renderDiagnosticSpecial(){
  const scores=toolkitJson("biaV4Diagnostic",{}), vals=Object.values(scores).map(Number), avg=vals.length?vals.reduce((a,b)=>a+b,0)/vals.length:0;
  const ranked=DIAGNOSTIC_DOMAINS.filter(x=>Object.hasOwn(scores,x)).map(x=>[x,Number(scores[x])]).sort((a,b)=>a[1]-b[1]), risks=ranked.filter(x=>x[1]<2).slice(0,5), opportunities=ranked.filter(x=>x[1]>=2&&x[1]<4).slice(0,5), strengths=[...ranked].reverse().slice(0,5);
  const text=list=>list.length?list.map(x=>x[0]).join(" · "):"À renseigner";
  return `<div class="tool-block"><div class="section-title"><div><h2>Scoring terrain 0 à 5</h2><p class="hint">0 Inexistant · 1 Très faible · 2 Insuffisant · 3 Acceptable · 4 Maîtrisé · 5 Excellence</p></div><div class="diag-score" id="diagScore">${avg.toFixed(1)} / 5</div></div><div class="diag-radar" id="diagRadar">${renderDiagRadar(scores)}</div><p class="hint">Axes 1 à 26 dans l’ordre de la grille ci-dessous.</p><div class="diag-list">${DIAGNOSTIC_DOMAINS.map(x=>`<label class="diag-row"><span>${esc(x)}</span><select data-diag-domain="${esc(x)}"><option value="">—</option>${[0,1,2,3,4,5].map(n=>`<option value="${n}" ${String(scores[x])===String(n)?"selected":""}>${n} / 5</option>`).join("")}</select></label>`).join("")}</div><div class="section grid"><div class="fact-note"><b>Top risques :</b><br><span id="diagRisks">${esc(text(risks))}</span></div><div class="fact-note"><b>Top opportunités :</b><br><span id="diagOpportunities">${esc(text(opportunities))}</span></div><div class="fact-note"><b>Forces observées :</b><br><span id="diagStrengths">${esc(text(strengths))}</span></div><div class="fact-note"><b>Candidats quick wins :</b><br><span id="diagQuickWins">${esc(text(ranked.filter(x=>x[1]>=1&&x[1]<=2).slice(0,5)))}</span><br><small>À confirmer par impact / effort.</small></div></div></div><div class="tool-block"><h2>Diagnostic usine en 2 heures</h2><ol><li>00:00 — Direction site : attentes, risques, engagements client</li><li>00:15 — KPI : définitions, tendances, écarts majeurs</li><li>00:30 — Gemba : flux complet et files</li><li>01:30 — Synthèse factuelle et recoupement</li><li>01:50 — Top 3 problèmes et prochaines mesures</li></ol></div><div class="tool-block"><h2>Diagnostic d’un site en 1 journée</h2><ol><li>08h00 Direction site</li><li>08h30 KPI</li><li>09h00 Gemba</li><li>11h00 Production</li><li>12h00 Synthèse intermédiaire</li><li>13h00 Maintenance / Qualité / Supply</li><li>15h00 Analyse flux</li><li>16h00 Restitution provisoire</li><li>17h00 Top 5 problèmes / Top 5 actions</li></ol></div>`;
}

function renderDiagRadar(scores){
  const n=DIAGNOSTIC_DOMAINS.length,c=100,r=78,point=(i,value)=>{const a=-Math.PI/2+i*2*Math.PI/n,rr=r*value/5;return `${(c+Math.cos(a)*rr).toFixed(1)},${(c+Math.sin(a)*rr).toFixed(1)}`};
  const rings=[1,2,3,4,5].map(level=>`<polygon points="${DIAGNOSTIC_DOMAINS.map((_,i)=>point(i,level)).join(" ")}" fill="none" stroke="#d7e3e5" stroke-width="0.8"/>`).join(""), axes=DIAGNOSTIC_DOMAINS.map((_,i)=>`<line x1="100" y1="100" x2="${point(i,5).split(",")[0]}" y2="${point(i,5).split(",")[1]}" stroke="#e4ecee" stroke-width="0.6"/>`).join(""), shape=DIAGNOSTIC_DOMAINS.map((d,i)=>point(i,Number(scores[d]||0))).join(" ");
  return `<svg viewBox="0 0 200 200" role="img" aria-label="Radar de maturité 360 degrés">${rings}${axes}<polygon points="${shape}" fill="#087c7d44" stroke="#087c7d" stroke-width="2"/></svg>`;
}

function renderKpiSpecial(){
  return `<div class="tool-block"><h2>Hiérarchie recommandée</h2><div class="route-flow"><div><b>Direction Groupe</b><br>Sécurité, OTIF, qualité client, résultat économique, cash/stock, bénéfices progrès, people</div><div><b>Site</b><br>Leviers expliquant les résultats : TRS, FPY, adhérence, productivité, maintenance</div><div><b>Atelier</b><br>Mesures pilotables dans la journée : écart au plan, défauts, arrêts, WIP, présence</div><div><b>Chantier</b><br>Mesure directement liée au problème et à la cause testée</div></div></div><div class="tool-block data-table"><h2>Dictionnaire</h2><table><thead><tr><th>KPI</th><th>Formule</th><th>Unité</th><th>Intérêt</th><th>Fréquence</th><th>Propriétaire</th><th>Piège</th></tr></thead><tbody>${KPI_DICTIONARY.map(x=>`<tr>${x.map(v=>`<td>${esc(v)}</td>`).join("")}</tr>`).join("")}</tbody></table></div>`;
}

function renderQuestionsSpecial(){
  const roles=Object.keys(ROLE_QUESTIONS), role=toolkitState.questionRole in ROLE_QUESTIONS?toolkitState.questionRole:roles[0], questions=[...ROLE_QUESTIONS[role],...COMMON_QUESTIONS].slice(0,20);
  return `<div class="tool-block"><h2>Choisir l’interlocuteur</h2><div class="question-role">${roles.map(x=>`<button class="chip ${x===role?"active":""}" data-question-role="${esc(x)}">${esc(x)}</button>`).join("")}</div><ol>${questions.map(x=>`<li>${esc(x)}</li>`).join("")}</ol></div>`;
}

function renderEvidenceSpecial(){
  if(!(data.knowledgeSources||[]).length)data.knowledgeSources=toolkitJson("biaV4KnowledgeSources",[]);
  const items=data.knowledgeSources||[], label={fait_verifie:"A · Fait vérifié",hypothese_probable:"B · Hypothèse probable",point_a_confirmer:"C · Point à confirmer"}, tone={fait_verifie:"verified",hypothese_probable:"hypothesis",point_a_confirmer:"confirm"};
  return `<div class="tool-block"><h2>Règle absolue sur les informations BIA</h2><div class="source-class"><div class="verified"><b>A · Fait vérifié</b><br>Source publique identifiable, lien fonctionnel et date de consultation.</div><div class="hypothesis"><b>B · Hypothèse probable</b><br>Déduction raisonnable explicitement présentée comme hypothèse.</div><div class="confirm"><b>C · Point à confirmer</b><br>Information à vérifier lors d’un entretien, d’une visite ou dans les systèmes.</div></div></div><form class="form tool-block" id="knowledgeForm"><h2>Ajouter une information</h2><div class="form-grid"><label>Classement<select id="knowledgeClass"><option value="point_a_confirmer">C · Point à confirmer</option><option value="hypothese_probable">B · Hypothèse probable</option><option value="fait_verifie">A · Fait vérifié</option></select></label><label>Titre<input id="knowledgeTitle" required placeholder="Ex. Périmètre d’un site"></label><label class="wide">Information<textarea id="knowledgeStatement" required rows="3" placeholder="Formulation précise, sans transformer une hypothèse en fait"></textarea></label><label>Source publique<input id="knowledgeUrl" type="url" placeholder="https://…"></label><label>Date de consultation<input id="knowledgeDate" type="date"></label><label>Validation terrain par<input id="knowledgeOwner" placeholder="Rôle ou personne"></label></div><div class="form-footer"><button class="btn">Enregistrer dans le registre</button></div></form><div class="tool-block"><div class="section-title"><h2>Registre</h2><span class="badge">${items.length}</span></div><div class="list">${items.map(x=>`<article class="row source-row ${tone[x.classification]||"confirm"}"><div class="card-top"><span class="pill open">${esc(label[x.classification]||x.classification)}</span><span class="row-meta">${x.consulted_at?new Date(x.consulted_at).toLocaleDateString("fr-FR"):"Sans date"}</span></div><div class="row-title">${esc(x.title)}</div><p class="hint">${esc(x.statement)}</p><div class="row-meta">${x.source_url?esc(x.source_url):"Source non requise / à compléter"}${x.validation_owner?" · Validation : "+esc(x.validation_owner):""}</div></article>`).join("")||empty("Aucune information enregistrée.")}</div></div>`;
}

function bindToolkit(){
  document.querySelectorAll("[data-open-tool]").forEach(b=>b.onclick=()=>{toolkitState.module=b.dataset.openTool;toolkitState.problem=null;renderToolkit();bindToolkit();window.scrollTo({top:0,behavior:"smooth"})});
  document.querySelectorAll("[data-problem-route]").forEach(b=>b.onclick=()=>{toolkitState.problem=b.dataset.problemRoute;toolkitState.module=null;renderToolkit();bindToolkit();window.scrollTo({top:0,behavior:"smooth"})});
  document.querySelectorAll("[data-back-tools]").forEach(b=>b.onclick=()=>{toolkitState.module=null;toolkitState.problem=null;renderToolkit();bindToolkit();window.scrollTo({top:0,behavior:"smooth"})});
  document.querySelectorAll("[data-tool-category]").forEach(b=>b.onclick=()=>{toolkitState.category=b.dataset.toolCategory;renderToolkit();bindToolkit()});
  document.querySelectorAll("[data-start-tool]").forEach(b=>b.onclick=()=>startToolkitRun(b.dataset.startTool));
  document.querySelectorAll("[data-tool-action]").forEach(b=>b.onclick=()=>createToolkitAction(b.dataset.toolAction));
  document.querySelectorAll("[data-problem-action]").forEach(b=>b.onclick=()=>createProblemAction(b.dataset.problemAction));
  document.querySelectorAll("[data-print-tool]").forEach(b=>b.onclick=()=>window.print());
  document.querySelectorAll("[data-tool-check]").forEach(b=>b.onchange=updateToolProgress);
  document.querySelectorAll("[data-diag-domain]").forEach(b=>b.onchange=updateDiagnostic);
  document.querySelectorAll("[data-question-role]").forEach(b=>b.onclick=()=>{toolkitState.questionRole=b.dataset.questionRole;renderToolkit();bindToolkit()});
  $("knowledgeForm")?.addEventListener("submit",createKnowledgeSource);
  const search=$("toolSearch"); if(search)search.oninput=()=>filterToolkit(search.value);
  const clear=$("clearToolSearch"); if(clear)clear.onclick=()=>{search.value="";filterToolkit("");search.focus()};
}

function filterToolkit(value){
  const q=value.trim().toLowerCase();let shown=0;
  document.querySelectorAll(".toolkit-searchable").forEach(x=>{const ok=!q||(x.dataset.searchText||"").includes(q);x.hidden=!ok;if(ok)shown++});
  const emptyNode=$("toolNoResult");if(emptyNode)emptyNode.hidden=shown>0;
}

function updateToolProgress(e){
  const module=e.target.dataset.module,index=Number(e.target.dataset.toolCheck),all=toolkitJson("biaV4ToolProgress",{}),done=new Set(all[module]||[]);
  e.target.checked?done.add(index):done.delete(index);all[module]=[...done].sort((a,b)=>a-b);toolkitSave("biaV4ToolProgress",all);
  const total=toolkitModule(module)?.checklist.length||1,pct=Math.round(done.size/total*100);if($("toolProgressText"))$("toolProgressText").textContent=pct+" %";if($("toolProgressBar"))$("toolProgressBar").style.width=pct+"%";
}

function updateDiagnostic(e){
  const scores=toolkitJson("biaV4Diagnostic",{});if(e.target.value==="")delete scores[e.target.dataset.diagDomain];else scores[e.target.dataset.diagDomain]=Number(e.target.value);toolkitSave("biaV4Diagnostic",scores);
  const vals=Object.values(scores).map(Number),avg=vals.length?vals.reduce((a,b)=>a+b,0)/vals.length:0,ranked=DIAGNOSTIC_DOMAINS.filter(x=>Object.hasOwn(scores,x)).map(x=>[x,Number(scores[x])]).sort((a,b)=>a[1]-b[1]), text=list=>list.length?list.map(x=>x[0]).join(" · "):"À renseigner";
  if($("diagScore"))$("diagScore").textContent=avg.toFixed(1)+" / 5";if($("diagRadar"))$("diagRadar").innerHTML=renderDiagRadar(scores);if($("diagRisks"))$("diagRisks").textContent=text(ranked.filter(x=>x[1]<2).slice(0,5));if($("diagOpportunities"))$("diagOpportunities").textContent=text(ranked.filter(x=>x[1]>=2&&x[1]<4).slice(0,5));if($("diagStrengths"))$("diagStrengths").textContent=text([...ranked].reverse().slice(0,5));if($("diagQuickWins"))$("diagQuickWins").textContent=text(ranked.filter(x=>x[1]>=1&&x[1]<=2).slice(0,5));
}

async function createKnowledgeSource(e){
  e.preventDefault();const classification=$("knowledgeClass").value, source_url=$("knowledgeUrl").value||null, consulted_at=$("knowledgeDate").value||null;if(classification==="fait_verifie"&&(!source_url||!consulted_at))return toast("Un fait vérifié exige une source et une date de consultation.");
  const item={id:"local-knowledge-"+Date.now(),classification,title:$("knowledgeTitle").value,statement:$("knowledgeStatement").value,source_url,consulted_at,validation_owner:$("knowledgeOwner").value||null,status:"ouvert",created_at:new Date().toISOString()};data.knowledgeSources??=[];data.knowledgeSources.unshift(item);toolkitSave("biaV4KnowledgeSources",data.knowledgeSources.filter(x=>String(x.id).startsWith("local-")));
  const saved=await write("knowledge_sources",{classification:item.classification,title:item.title,statement:item.statement,source_url:item.source_url,consulted_at:item.consulted_at,validation_owner:item.validation_owner,status:item.status});if(saved)Object.assign(item,saved);toast(saved?"Information classée et synchronisée.":"Information classée sur cet appareil.");renderToolkit();bindToolkit();
}

async function startToolkitRun(moduleId){
  const module=toolkitModule(moduleId);if(!module)return;
  const run={id:"local-tool-"+Date.now(),site_id:siteId,module_id:module.id,title:module.title,status:"en_cours",progress:{},started_at:new Date().toISOString(),created_at:new Date().toISOString()};
  data.toolkitRuns??=[];data.toolkitRuns.unshift(run);toolkitSave("biaV4ToolkitRuns",data.toolkitRuns.filter(x=>String(x.id).startsWith("local-")));
  const saved=await write("toolkit_runs",{site_id:siteId,module_id:module.id,title:module.title,status:"en_cours",progress:{},started_at:run.started_at});if(saved)Object.assign(run,saved);
  toast(saved?"Parcours démarré et synchronisé.":"Parcours démarré sur cet appareil.");
}

async function createToolkitAction(moduleId){
  const module=toolkitModule(moduleId);if(!module)return;const title=module.title+" · "+module.steps[0];
  const action={id:"local-tool-action-"+Date.now(),site_id:siteId,title,owner:"À attribuer",priority:"Moyenne",status:"Ouverte",origin_type:"Bibliothèque",description:module.objective};data.actions.unshift(action);
  const saved=await write("actions",{site_id:siteId,title,owner:action.owner,priority:action.priority,status:action.status,origin_type:action.origin_type,description:action.description});if(saved)Object.assign(action,saved);toast("Action créée depuis la bibliothèque.");
}

async function createProblemAction(problemId){
  const route=toolkitProblem(problemId);if(!route)return;const action={id:"local-problem-action-"+Date.now(),site_id:siteId,title:route.first,owner:"À attribuer",priority:"Moyenne",status:"Ouverte",origin_type:"Arbre de décision",description:route.problem+" · Mesure : "+route.measure};data.actions.unshift(action);
  const saved=await write("actions",{site_id:siteId,title:action.title,owner:action.owner,priority:action.priority,status:action.status,origin_type:action.origin_type,description:action.description});if(saved)Object.assign(action,saved);toast("Première action créée.");
}
