"use strict";

function launchAction(button) {
  const id=button.dataset.originId,info=recordMeta(id);
  if(!requestCloseModal())return;
  actionForm(null,{origin_type:button.dataset.originType||(info?.key==="decisions"?"Décision":"Problème"),origin_id:id||null,site_id:info?.row.site_id==="group"?null:info?.row.site_id,description:info?.row.description||info?.row.title||info?.row.finding||""});
}
function actionForm(existing=null,origin={}) {
  if(existing&&!allowedSite(existing.site_id))return;
  const ref=recordMeta(existing?.origin_id||origin.origin_id),siteId=existing?.site_id||origin.site_id||(state.site==="group"?"marzin":state.site),readOnly=state.role==="dg";
  if(readOnly)return modal(`${existing?.id||"Action"} · Consultation`,`<h3>${esc(existing?.title||"")}</h3><p>${esc(existing?.description||"")}</p><p>${esc(existing?.owner)} · ${shortDate(existing?.due_date)} · ${esc(existing?.status)}</p><p>${esc(existing?.effectiveness||"Efficacité non encore vérifiée")}</p>${recordLink(existing?.origin_id,"Origine")}`);
  modal(existing?`${existing.id} · Action`:"Nouvelle action",`<form id="actionForm"><p class="hint">Une action = un résultat attendu, un responsable, une date.</p>${ref?`<div class="context-strip">Origine : ${esc(ref.row.id)} · ${esc(ref.row.title||ref.row.description||ref.row.zone||ref.row.scope)}</div>`:""}<div class="form-grid section">
    <label class="wide">Que faut-il faire ?<input id="actionTitle" required value="${esc(existing?.title||origin.title||"")}" placeholder="Ex. Remplacer le guide usé du poste 4"></label>
    <label>Responsable<input id="actionOwner" value="${esc(existing?.owner||origin.owner||"")}" required placeholder="Nom ou équipe"></label>
    <label>Pour quand ?<input id="actionDue" type="date" value="${existing?.due_date||origin.due_date||today()}" required></label>
    <label>Priorité<select id="actionPriority">${["Normale","Haute","Critique"].map(x=>`<option ${x===(existing?.priority||origin.priority||"Normale")?"selected":""}>${x}</option>`).join("")}</select></label>
    <label>Statut<select id="actionStatus">${ACTION_STATES.map(x=>`<option ${x===(existing?.status||"Ouverte")?"selected":""}>${x}</option>`).join("")}</select></label>
    <label>Site<select id="actionSite" ${ref&&ref.row.site_id!=="group"?"disabled":""}>${siteOptions(siteId)}</select></label>
    <label class="wide">Contexte et résultat attendu<textarea id="actionDescription" rows="3">${esc(existing?.description||origin.description||"")}</textarea></label>
  </div><fieldset id="actionVerification" class="verification-box section"><legend>Vérifier l’efficacité</legend><label class="field">Résultat observé et période de tenue<textarea id="actionEvidence" rows="3" placeholder="Ex. 0 défaut sur trois lots contrôlés">${esc(existing?.effectiveness||"")}</textarea></label><div class="form-grid section"><label>Vérifié par<input id="actionVerifier" value="${esc(existing?.verified_by||"")}"></label><label>Date de vérification<input type="date" id="actionVerifiedAt" value="${existing?.verified_at||today()}"></label></div></fieldset>${existing?historyView(existing):""}<div class="form-actions"><button class="btn">Enregistrer l’action</button><button type="button" class="btn secondary" data-close-modal>Annuler</button></div></form>`);
  const visibility=()=>{$("actionVerification").hidden=!["À vérifier","Clôturée"].includes($("actionStatus").value);};$("actionStatus").onchange=visibility;visibility();
  $("actionForm").onsubmit=e=>{
    e.preventDefault();const status=$("actionStatus").value,evidence=$("actionEvidence").value.trim(),verifier=$("actionVerifier").value.trim(),verifiedAt=$("actionVerifiedAt").value,chosenSite=$("actionSite").value;
    if(!allowedSite(chosenSite,true))return toast("Site hors de votre périmètre.");
    if(ref&&ref.row.site_id!=="group"&&ref.row.site_id!==chosenSite)return toast("L’action doit rester sur le site de son origine.");
    if(status==="Clôturée"&&(!evidence||!verifier||!verifiedAt||verifiedAt>today()))return toast("Pour clore : résultat constaté, vérificateur et date passée ou du jour requis.");
    const id=existing?.id||nextId("A",data.actions),payload={id,site_id:chosenSite,workshop_id:existing?.workshop_id||origin.workshop_id||data.workshops.find(w=>w.site_id===chosenSite)?.id||null,title:$("actionTitle").value.trim(),owner:$("actionOwner").value.trim(),due_date:$("actionDue").value,priority:$("actionPriority").value,status,description:$("actionDescription").value.trim(),origin_type:existing?.origin_type||origin.origin_type||"Manuel",origin_id:existing?.origin_id||origin.origin_id||null,observation_id:existing?.observation_id||origin.observation_id||null,effectiveness:evidence||null,verified_by:verifier||null,verified_at:status==="Clôturée"?verifiedAt:null,created_at:existing?.created_at||now(),updated_at:now()};
    if(!payload.title||!payload.owner)return toast("Précisez l’action et son responsable.");
    if(!commitData(()=>{let a=data.actions.find(x=>x.id===id);if(a)Object.assign(a,payload);else {a=payload;data.actions.unshift(a);}recordHistory(a,status,evidence);const p=data.problems.find(x=>x.id===a.origin_id);if(p&&!p.action_ids.includes(id))p.action_ids.push(id);const signal=data.signals.find(x=>x.id===a.origin_id);if(signal){signal.action_id=id;if(["Nouveau","Pris en compte"].includes(signal.state)){signal.state="Action en cours";signal.owner=payload.owner;recordHistory(signal,signal.state,`Action ${id}`);}}}))return;
    closeModal();receipt(id,"Actions",chosenSite,status==="À vérifier"?"Vérifier le résultat sur le terrain":"Suivre l’échéance et le résultat");render();
  };
}
function advanceAction(id) {
  const a=data.actions.find(x=>x.id===id);if(!a||!allowedSite(a.site_id,true))return;
  if(a.status==="À vérifier")return actionForm(a);
  if(a.status==="Clôturée")return;
  const status=a.status==="Ouverte"?"En cours":"À vérifier";
  if(!commitData(()=>{const row=data.actions.find(x=>x.id===id);row.status=status;recordHistory(row,status);}))return;
  receipt(id,"Actions",a.site_id,status==="À vérifier"?"Ouvrir pour renseigner la preuve d’efficacité":"Action démarrée");render();
}
function newSignalForm(existing=null) {
  const siteId=existing?.site_id||(state.site==="group"?"marzin":state.site);
  if(!allowedSite(siteId,true))return;
  modal(existing?`${existing.id} · Modifier le signal`:"Nouveau Signal Terrain",`<form id="signalForm"><p class="hint">Décrivez ce que vous voyez. Le lieu et l’heure sont conservés avec le signal.</p><div class="form-grid"><label>Type<select id="signalType">${SIGNAL_TYPES.map(t=>`<option ${t===(existing?.type||"Production")?"selected":""}>${t}</option>`).join("")}</select></label><label>Gravité<select id="signalSeverity">${["À qualifier","Normale","Haute","Critique"].map(t=>`<option ${t===(existing?.severity||"À qualifier")?"selected":""}>${t}</option>`).join("")}</select></label><label>Site<select id="signalSite" ${existing?"disabled":""}>${siteOptions(siteId)}</select></label><label>Atelier<select id="signalWorkshop"></select></label><label class="wide">Que se passe-t-il ?<textarea id="signalDescription" rows="3" required placeholder="Ex. Le guide de la scie bouge pendant la coupe.">${esc(existing?.description||"")}</textarea></label></div><details class="section"><summary>Préciser le lieu, joindre une photo ou noter la réaction immédiate</summary><div class="form-grid section"><label>Zone / poste<input id="signalZone" value="${esc(existing?.zone||"")}"></label><label>Auteur / équipe<input id="signalAuthor" value="${esc(existing?.author||"")}" placeholder="Facultatif"></label><label class="wide">Action immédiate<textarea id="signalImmediate" rows="2">${esc(existing?.immediate_action||"")}</textarea></label><label class="wide">Photo facultative<input type="file" id="signalPhoto" accept="image/jpeg,image/png,image/webp"><span id="signalPhotoPreview">${photoImage(existing?.photo)}</span></label></div></details><div class="alert critical section" id="criticalReminder" hidden>Risque immédiat : sécurisez et alertez selon la consigne du site avant la saisie.</div><div class="form-actions"><button class="btn">${existing?"Enregistrer":"Envoyer le signal"}</button><button type="button" class="btn secondary" data-close-modal>Annuler</button></div></form>`);
  const workshops=()=>{$("signalWorkshop").innerHTML='<option value="">Atelier non précisé</option>'+data.workshops.filter(w=>w.site_id===$("signalSite").value).map(w=>`<option value="${w.id}" ${w.id===existing?.workshop_id?"selected":""}>${esc(w.name)}</option>`).join("");};workshops();$("signalSite").onchange=workshops;
  $("signalSeverity").onchange=()=>$("criticalReminder").hidden=$("signalSeverity").value!=="Critique";
  const photo=photoPicker("signalPhoto","signalPhotoPreview",existing?.photo);
  $("signalForm").onsubmit=e=>{e.preventDefault();if(photo.busy||photo.error)return toast("Attendez la préparation de la photo ou choisissez une image valide.");const id=existing?.id||nextId("S",data.signals),payload={...existing,id,site_id:$("signalSite").value,workshop_id:$("signalWorkshop").value||null,type:$("signalType").value,severity:$("signalSeverity").value,description:$("signalDescription").value.trim(),zone:$("signalZone").value.trim(),author:$("signalAuthor").value.trim()||"Équipe terrain",immediate_action:$("signalImmediate").value.trim(),photo:photo.value,state:existing?.state||"Nouveau",created_at:existing?.created_at||now(),updated_at:now()};if(!payload.description||!allowedSite(payload.site_id,true))return toast("Précisez un fait et un site autorisé.");if(!commitData(()=>{const row=data.signals.find(s=>s.id===id);if(row)Object.assign(row,payload);else data.signals.unshift(payload);recordHistory(row||payload,payload.state,existing?"Signal modifié":"Signal créé");}))return;closeModal();state.site=payload.site_id;state.view="terrain";state.terrainTab="signals";state.signalFilter="open";receipt(id,"Terrain → Signal Terrain",payload.site_id,"Attribuer un responsable");render();openSignal(id);};
}
function signalNextLabel(s) {return {Nouveau:"Prendre en compte","Pris en compte":"Démarrer le traitement","Action en cours":"Déclarer la résolution",Résolu:"Vérifier l’efficacité",Vérifié:"Clore le signal",Clos:"Consulter"}[s.state]||"Consulter";}
function openSignal(id) {
  const s=data.signals.find(x=>x.id===id);if(!s||!allowedSite(s.site_id))return;
  const index=SIGNAL_STATES.indexOf(s.state);
  modal(`${s.id} · Signal Terrain`,`<div class="row-top">${pill(s.type,"info")}${pill(s.state,signalTone(s))}</div><h3>${esc(s.description)}</h3><p class="hint">${esc(getSiteName(s.site_id))} · ${esc(s.zone||"Zone non précisée")} · ${shortDate(s.created_at)} · ${esc(s.author)}</p><div class="workflow section">${SIGNAL_STATES.map((x,i)=>`<span class="workflow-step ${i<index?"done":i===index?"active":""}">${x}</span>`).join("")}</div>${photoImage(s.photo)}<div class="grid cols-2 section"><section class="panel"><h3>Réaction immédiate</h3><p>${esc(s.immediate_action||"Non renseignée")}</p></section><section class="panel"><h3>Prochaine étape</h3><p>${esc(s.state==="Clos"?"Signal clos après vérification":signalNextLabel(s))}</p><p class="hint">Responsable : ${esc(s.owner||"À attribuer")}</p></section></div><div class="row-actions section">${recordLink(s.action_id,"Action")}${recordLink(s.problem_id,"Problème")}${recordLink(s.origin_id,"Origine")}</div>${s.resolution?`<p><b>Résolution :</b> ${esc(s.resolution)}</p>`:""}${s.verification?`<p><b>Vérification :</b> ${esc(s.verification)} · ${esc(s.verified_by)}</p>`:""}<div class="form-actions">${allowedSite(s.site_id,true)&&s.state!=="Clos"?`<button class="btn" data-advance-signal="${s.id}">${esc(signalNextLabel(s))}</button>${!s.action_id?`<button class="btn secondary" data-signal-action="${s.id}">Créer une action</button>`:""}${!s.problem_id&&role().nav.includes("resolution")?`<button class="btn secondary" data-problem-from-signal="${s.id}">Ouvrir A3 / 8D / QRQC</button>`:""}<button class="btn ghost" data-edit-signal="${s.id}">Corriger le signal</button>`:""}</div>${historyView(s)}`);
  document.querySelectorAll("[data-edit-signal]").forEach(b=>b.onclick=()=>newSignalForm(s));
  document.querySelectorAll("[data-signal-action]").forEach(b=>b.onclick=()=>actionForm(null,{site_id:s.site_id,workshop_id:s.workshop_id,title:`Traiter · ${s.description}`,priority:s.severity==="Critique"?"Critique":"Haute",origin_type:"Signal",origin_id:s.id,description:s.description}));
}
function advanceSignal(id) {
  const s=data.signals.find(x=>x.id===id);if(!s||!allowedSite(s.site_id,true)||s.state==="Clos")return;
  const next=SIGNAL_STATES[SIGNAL_STATES.indexOf(s.state)+1],needsProof=["Résolu","Vérifié","Clos"].includes(next),open=linkedActions(id).filter(isOpenAction);
  if(next==="Clos"&&(open.length||s.action_id&&data.actions.some(a=>a.id===s.action_id&&isOpenAction(a))))return toast("L’action liée doit être vérifiée et clôturée avant le signal.");
  if(next==="Clos"&&s.problem_id&&data.problems.some(p=>p.id===s.problem_id&&p.status!=="Clos"))return toast("Terminez et vérifiez le dossier de résolution lié avant de clore le signal.");
  modal(`${s.id} · ${signalNextLabel(s)}`,`<form id="signalTransition"><p>${esc(s.description)}</p><label class="field">Responsable du traitement<input id="transitionOwner" required value="${esc(s.owner||"")}"></label>${needsProof?`<label class="field section">${next==="Résolu"?"Qu’est-ce qui a résolu le problème ?":"Quel résultat prouve l’efficacité ?"}<textarea id="transitionEvidence" required rows="3">${esc(next==="Résolu"?s.resolution||"":s.verification||"")}</textarea></label>`:""}${["Vérifié","Clos"].includes(next)?`<label class="field section">Vérifié par<input id="transitionVerifier" required value="${esc(s.verified_by||"")}"></label>`:""}<div class="form-actions"><button class="btn">${esc(signalNextLabel(s))}</button><button type="button" class="btn secondary" data-close-modal>Annuler</button></div></form>`);
  $("signalTransition").onsubmit=e=>{e.preventDefault();const owner=$("transitionOwner").value.trim(),evidence=$("transitionEvidence")?.value.trim(),verifier=$("transitionVerifier")?.value.trim();if(!owner||needsProof&&!evidence||["Vérifié","Clos"].includes(next)&&!verifier)return toast("Complétez le responsable et les preuves demandées.");if(!commitData(()=>{const r=data.signals.find(x=>x.id===id);r.owner=owner;r.state=next;if(next==="Pris en compte")r.taken_at=now();if(next==="Résolu"){r.resolution=evidence;r.resolved_at=now();}if(["Vérifié","Clos"].includes(next)){r.verification=evidence;r.verified_by=verifier;r.verified_at=now();}if(next==="Clos")r.closed_at=now();recordHistory(r,next,evidence||`Pris en charge par ${owner}`);}))return;closeModal();receipt(id,"Terrain → Signal Terrain",s.site_id,next);render();openSignal(id);};
}
function createProblemRecord({title,site_id,method="A3",owner="",context="",signal_id=null,origin_id=null,observation_id=null}) {
  const id=nextId("P",data.problems),p={id,site_id,title,method,status:"Cadrage",owner,signal_ids:signal_id?[signal_id]:[],action_ids:[],content:{context},origin_id,observation_id,created_at:now(),updated_at:now()};
  data.problems.unshift(p);const doc={id:nextId("DOC",data.documents),site_id,type:method,title,owner,status:"Brouillon",problem_id:id,structured_data:initialDocumentData(method,p,context),version:1,created_at:now(),updated_at:now()};data.documents.unshift(doc);
  if(signal_id){const s=data.signals.find(x=>x.id===signal_id);if(s){s.problem_id=id;recordHistory(s,s.state,`Dossier ${method} ${id}`);}}
  return {problem:p,document:doc};
}
function genericProblemForm(origin={}) {
  if(!role().nav.includes("resolution"))return;
  const siteId=origin.site_id||(state.site==="group"?"marzin":state.site);
  modal("Démarrer une résolution de problème",`<form id="problemForm"><div class="form-grid"><label class="wide">Quel problème faut-il résoudre ?<input id="problemTitle" required value="${esc(origin.title||"")}"></label><label>Méthode<select id="problemMethod">${["A3","8D","QRQC"].map(m=>`<option ${origin.method===m?"selected":""}>${m}</option>`).join("")}</select></label><label>Responsable<input id="problemOwner" required value="${esc(origin.owner||"")}"></label><label>Site<select id="problemSite" ${origin.site_id?"disabled":""}>${siteOptions(siteId)}</select></label><label class="wide">Faits de départ<textarea id="problemContext" rows="3">${esc(origin.description||"")}</textarea></label></div><div class="method-choice"><p><b>A3</b> : comprendre et traiter un problème récurrent.</p><p><b>8D</b> : sécuriser le client, supprimer apparition et non-détection.</p><p><b>QRQC</b> : organiser une réaction qualité rapide.</p></div><div class="form-actions"><button class="btn">Créer et commencer</button><button type="button" class="btn secondary" data-close-modal>Annuler</button></div></form>`);
  $("problemForm").onsubmit=e=>{e.preventDefault();let created;const payload={title:$("problemTitle").value.trim(),owner:$("problemOwner").value.trim(),method:$("problemMethod").value,site_id:$("problemSite").value,context:$("problemContext").value.trim(),signal_id:origin.signal_id,origin_id:origin.origin_id};if(!payload.title||!payload.owner||!allowedSite(payload.site_id,true))return toast("Précisez le problème, le responsable et le site.");if(!commitData(()=>{created=createProblemRecord(payload);}))return;closeModal();state.site=payload.site_id;state.view="resolution";state.selectedProblemId=created.problem.id;receipt(created.document.id,"Documents et Résolution",payload.site_id,"Compléter la première étape");render();editDocument(created.document.id);};
}
function problemFromSignal(id) {const s=data.signals.find(x=>x.id===id);if(!s)return;if(s.problem_id)return openRecord(s.problem_id);genericProblemForm({site_id:s.site_id,title:s.description,description:[s.description,s.zone,s.immediate_action].filter(Boolean).join(" · "),signal_id:id,origin_id:id,owner:s.owner||""});}
function openSubject(id) {openRecord(id);}
function editProblem(id) {const doc=data.documents.find(d=>d.problem_id===id);if(doc)return editDocument(doc.id);const p=data.problems.find(x=>x.id===id);if(!p)return;let d;if(!commitData(()=>{d={id:nextId("DOC",data.documents),site_id:p.site_id,type:p.method,title:p.title,owner:p.owner,status:"Brouillon",problem_id:id,structured_data:initialDocumentData(p.method,p),version:1,updated_at:now()};data.documents.unshift(d);} ))return;editDocument(d.id);}

function renderPractices() {
  const rows=scoped(data.practices);
  return `${pageHead("Capitalisation","Bonnes pratiques","Un résultat prouvé, des conditions de transfert et une validation avant diffusion.",state.role!=="dg"?'<button class="btn" data-new-practice>＋ Proposer une pratique</button>':"")}${listSearch()}<div class="grid cols-2">${rows.map(p=>`<article class="panel" data-search-row><div class="row-top">${pill(p.status,p.status==="Publiée"?"done":"progress")}<span>${esc(p.id)}</span></div><h3>${esc(p.title)}</h3><p>${esc(p.summary)}</p><p class="hint">${esc(getSiteName(p.site_id))}</p>${recordLink(p.id,"Consulter")}</article>`).join("")||empty("Aucune bonne pratique. Proposez une amélioration dont le résultat a été vérifié.")}</div>`;
}
function practiceForm(existing=null) {
  const siteId=existing?.site_id||(state.site==="group"?"marzin":state.site);
  if(!allowedSite(siteId))return;
  if(state.role==="dg")return modal(existing.title,`<p>${esc(existing.summary)}</p><h3>Résultat vérifié</h3><p>${esc(existing.evidence)}</p><h3>Conditions de transfert</h3><p>${esc(existing.transfer||"À préciser")}</p>${historyView(existing)}`);
  modal(existing?`${existing.id} · Bonne pratique`:"Proposer une bonne pratique",`<form id="practiceForm"><div class="form-grid"><label class="wide">Titre<input id="practiceTitle" required value="${esc(existing?.title||"")}"></label><label>Site source<select id="practiceSite">${siteOptions(siteId)}</select></label><label>Catégorie<select id="practiceCategory">${SIGNAL_TYPES.map(x=>`<option ${x===existing?.category?"selected":""}>${x}</option>`).join("")}</select></label><label class="wide">Comment cela fonctionne-t-il ?<textarea id="practiceSummary" required rows="3">${esc(existing?.summary||"")}</textarea></label><label class="wide">Résultat vérifié et preuve<textarea id="practiceEvidence" required rows="3">${esc(existing?.evidence||"")}</textarea></label><label class="wide">Conditions pour le reproduire ailleurs<textarea id="practiceTransfer" rows="3" placeholder="Prérequis, limites, formation nécessaire">${esc(existing?.transfer||"")}</textarea></label><label>Statut<select id="practiceStatus">${["À valider","À compléter",...(state.role==="lean"?["Publiée"]:[])].map(x=>`<option ${x===existing?.status?"selected":""}>${x}</option>`).join("")}</select></label><label>Validé par<input id="practiceValidator" value="${esc(existing?.validated_by||"")}"></label></div>${existing?historyView(existing):""}<div class="form-actions"><button class="btn">Enregistrer la pratique</button><button type="button" class="btn secondary" data-close-modal>Annuler</button></div></form>`);
  $("practiceForm").onsubmit=e=>{e.preventDefault();const payload={id:existing?.id||nextId("BP",data.practices),site_id:$("practiceSite").value,title:$("practiceTitle").value.trim(),category:$("practiceCategory").value,summary:$("practiceSummary").value.trim(),evidence:$("practiceEvidence").value.trim(),transfer:$("practiceTransfer").value.trim(),status:$("practiceStatus").value,validated_by:$("practiceValidator").value.trim(),created_at:existing?.created_at||now(),updated_at:now()};if(payload.status==="Publiée"&&(!payload.transfer||!payload.validated_by||state.role!=="lean"))return toast("Pour publier : préciser les conditions de transfert et le validateur.");if(!commitData(()=>{const p=data.practices.find(x=>x.id===payload.id);if(p)Object.assign(p,payload);else data.practices.unshift(payload);recordHistory(p||payload,payload.status,payload.validated_by);} ))return;closeModal();receipt(payload.id,"Bonnes pratiques",payload.site_id,payload.status);render();};
}
